import React, { useState } from 'react';

interface ComponentSpec {
  id: string;
  name: string;
  badge: string;
  color: string;
  responsibility: string;
  withoutIt: string;
  implementation: string;
}

const COMPONENTS: ComponentSpec[] = [
  {
    id: 'router',
    name: 'Tool Router & Dispatcher',
    badge: 'DISPATCH',
    color: '#38bdf8', // Sky Blue
    responsibility: 'Parses tool call intents generated by LLM, validates parameter types against JSON schema, and routes execution to registered functions.',
    withoutIt: 'Agent fails with type errors or executes invalid tool signatures.',
    implementation: 'def execute_tool(name: str, args: dict) -> JSON:\n    validate_schema(name, args)\n    return registry[name](**args)'
  },
  {
    id: 'risk',
    name: 'Risk Classifier Engine',
    badge: 'SECURITY',
    color: '#f87171', // Red
    responsibility: 'Classifies every action into Low (read-only), Medium (write state), or High Risk (destructive DB drop, network curl, financial transfer).',
    withoutIt: 'Agent executes dangerous or irreversible actions blindly on host OS.',
    implementation: 'def classify_risk(name, args) -> RiskLevel:\n    if name in DESTRUCTIVE_TOOLS:\n        return RiskLevel.HIGH'
  },
  {
    id: 'sandbox',
    name: 'Sandboxed Code Runtime',
    badge: 'ISOLATION',
    color: '#a78bfa', // Purple
    responsibility: 'Executes arbitrary code or shell commands inside restricted gVisor, Firecracker MicroVM, or Docker containers without host OS access.',
    withoutIt: 'Container escape, host filesystem deletion (`rm -rf /`), or credential theft.',
    implementation: 'docker_client.containers.run("agent-sandbox:latest", command=cmd, network_mode="none", mem_limit="512m")'
  },
  {
    id: 'hitl',
    name: 'Human-In-The-Loop (HITL) Gate',
    badge: 'APPROVAL',
    color: '#fbbf24', // Amber
    responsibility: 'Pauses execution graph when High-Risk action is flagged, emitting approval notification to human supervisor via Slack/Web UI.',
    withoutIt: 'No human oversight before executing production-impacting mutations.',
    implementation: 'if risk == RiskLevel.HIGH:\n    approved = await request_slack_approval(action)\n    if not approved: return "Action rejected"'
  },
  {
    id: 'guard',
    name: 'Budget & Loop Guard',
    badge: 'SAFETY',
    color: '#34d399', // Emerald
    responsibility: 'Enforces hard max-turn limits (e.g. 30 turns), cost ceilings (e.g. $5.00), timeout thresholds, and repeat-action stall detection.',
    withoutIt: 'Runaway infinite loops generating 50,000 API calls and a $500 surprise bill.',
    implementation: 'if turn_count >= MAX_TURNS or total_cost >= COST_CAP:\n    raise HarnessTerminationException("Limit exceeded")'
  },
  {
    id: 'obs',
    name: 'Observability & Audit Logger',
    badge: 'AUDIT',
    color: '#2dd4bf', // Teal
    responsibility: 'Captures structured telemetry, OpenTelemetry traces, token costs, and full audit logs of every input, tool call, and response.',
    withoutIt: 'Zero visibility into why an agent failed or how much a session cost.',
    implementation: 'telemetry.log_event("tool_executed", {"turn": turn, "tool": name, "cost": cost_usd, "duration_ms": elapsed})'
  }
];

export default function HarnessCoreComponentsDiagram() {
  const [activeId, setActiveId] = useState<string>('risk');
  const activeComp = COMPONENTS.find(c => c.id === activeId) || COMPONENTS[1];

  return (
    <div className="interactive-diagram-container" style={{ fontFamily: 'var(--ifm-font-family-base)' }}>
      {/* Header Bar */}
      <div className="interactive-diagram-header">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#a78bfa" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <rect x="2" y="2" width="20" height="8" rx="2" ry="2" />
          <rect x="2" y="14" width="20" height="8" rx="2" ry="2" />
          <line x1="6" y1="6" x2="6.01" y2="6" />
          <line x1="6" y1="18" x2="6.01" y2="18" />
        </svg>
        <span style={{ color: 'var(--ifm-color-content)', fontWeight: 600 }}>Production Agent Harness Core Components</span>
      </div>

      {/* Grid of Components */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
        gap: '10px',
        padding: '16px',
        background: '#0d0f1e',
        borderBottom: '1px solid #1e2342'
      }}>
        {COMPONENTS.map((comp) => {
          const isActive = activeId === comp.id;
          return (
            <button
              key={comp.id}
              onClick={() => setActiveId(comp.id)}
              style={{
                background: isActive ? `${comp.color}18` : '#13162b',
                border: `1.5px solid ${isActive ? comp.color : '#1e2342'}`,
                borderRadius: '8px',
                padding: '10px 12px',
                cursor: 'pointer',
                textAlign: 'left',
                transition: 'all 0.2s ease',
                boxShadow: isActive ? `0 0 12px ${comp.color}25` : 'none'
              }}
            >
              <div style={{ fontSize: '9px', fontWeight: 800, color: comp.color, background: `${comp.color}20`, padding: '2px 6px', borderRadius: '4px', display: 'inline-block', marginBottom: '4px' }}>
                {comp.badge}
              </div>
              <div style={{ fontSize: '12px', fontWeight: 700, color: 'var(--ifm-color-content)' }}>
                {comp.name}
              </div>
            </button>
          );
        })}
      </div>

      {/* Details Card */}
      <div className="interactive-diagram-details-card" style={{ background: '#090b14', padding: '20px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '12px' }}>
          <div style={{ width: '8px', height: '8px', borderRadius: '50%', background: activeComp.color }} />
          <div style={{ fontSize: '16px', fontWeight: 700, color: activeComp.color }}>
            {activeComp.name}
          </div>
        </div>

        <div style={{ fontSize: '13px', color: 'var(--ifm-color-content-secondary)', marginBottom: '14px', lineHeight: '1.5' }}>
          {activeComp.responsibility}
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '12px', marginBottom: '14px' }}>
          <div style={{ background: '#13162b', padding: '12px', borderRadius: '6px', border: '1px solid #f8717140' }}>
            <div style={{ fontSize: '11px', fontWeight: 700, color: '#f87171', textTransform: 'uppercase', marginBottom: '4px' }}>
              Catastrophic Risk Without It
            </div>
            <div style={{ fontSize: '12px', color: 'var(--ifm-color-content-secondary)' }}>
              {activeComp.withoutIt}
            </div>
          </div>

          <div style={{ background: '#13162b', padding: '12px', borderRadius: '6px', border: '1px solid #1e2342' }}>
            <div style={{ fontSize: '11px', fontWeight: 700, color: activeComp.color, textTransform: 'uppercase', marginBottom: '4px' }}>
              Implementation Code Pattern
            </div>
            <pre style={{
              background: '#090b14',
              padding: '8px',
              borderRadius: '4px',
              fontSize: '10px',
              color: 'var(--ifm-color-content)',
              margin: 0,
              whiteSpace: 'pre-wrap',
              fontFamily: 'monospace'
            }}>
              {activeComp.implementation}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}
