import React, { useState } from 'react';

export default function Iso20022MessageInspectorDiagram({ initialMsg = 'pacs008' }: { initialMsg?: 'pacs008' | 'pain001' | 'pacs002' | 'camt054' }): React.JSX.Element {
  const [selectedMsg, setSelectedMsg] = useState<'pacs008' | 'pain001' | 'pacs002' | 'camt054'>(initialMsg);
  const [selectedBlock, setSelectedBlock] = useState<'grpHdr' | 'txInf' | 'parties' | 'rmtInf'>('grpHdr');

  const messages = {
    pacs008: {
      name: 'pacs.008.001.08',
      title: 'Financial Institutional Customer Credit Transfer (A2A Clearing)',
      sender: 'Debtor Agent (Bank A)',
      receiver: 'Creditor Agent (Bank B) via Clearing (NPP/RTGS/SWIFT)',
      elements: {
        grpHdr: {
          tag: '<GrpHdr>',
          fields: [
            { name: 'MsgId', value: 'AU20260823NPP00123984', desc: 'Globally unique message identifier assigned by sender.' },
            { name: 'CreDtTm', value: '2026-08-23T14:30:00.120Z', desc: 'Exact creation timestamp in UTC format.' },
            { name: 'NbOfTxs', value: '1', desc: 'Number of individual transaction blocks in this message bundle.' },
            { name: 'SttlmInf', value: 'SttlmMtd = CLRG / ClrSys = AU.NPP', desc: 'Settlement Method: Instant settlement via NPP Clearing System.' }
          ]
        },
        txInf: {
          tag: '<CdtTrfTxInf>',
          fields: [
            { name: 'PmtId / EndToEndId', value: 'E2E-INV-2026-8849', desc: 'Immutable end-to-end reconciliation reference passed to creditor.' },
            { name: 'PmtId / UETR', value: 'c81b0e3e-63f2-4e92-9118-e21a2a9042b1', desc: 'SWIFT Universal End-to-End Tracking Reference (UUID v4).' },
            { name: 'IntrBkSttlmAmt', value: 'AUD 12,450.00', desc: 'Interbank settlement amount and ISO 4217 currency code.' },
            { name: 'ChrgBr', value: 'SLEV / SHAR', desc: 'Charge Bearer rule governing intermediary fee distribution.' }
          ]
        },
        parties: {
          tag: '<Dbtr> & <Cdtr>',
          fields: [
            { name: 'Dbtr (Debtor)', value: 'Acme Corp Pty Ltd (LEI: 5493006MHB84DD0Z7432)', desc: 'Originating payer legal entity identifier and name.' },
            { name: 'DbtrAgt (Bank A)', value: 'BICFI: ANZBAU3MXXX', desc: 'Debtor institution Business Identifier Code.' },
            { name: 'CdtrAgt (Bank B)', value: 'BICFI: WPACAU2SXXX', desc: 'Creditor institution Business Identifier Code.' },
            { name: 'Cdtr (Creditor)', value: 'Apex Logistics Global Pty Ltd', desc: 'Final beneficiary account owner.' }
          ]
        },
        rmtInf: {
          tag: '<RmtInf>',
          fields: [
            { name: 'Ustrd (Unstructured)', value: 'Invoice 8849 Supplier Payment August', desc: 'Free text narrative displayed on bank statements.' },
            { name: 'Strd / RfrdDocInf', value: 'Type: CINV / Nb: 8849 / RltdDt: 2026-08-20', desc: 'Structured Commercial Invoice metadata enabling automated ERP matching.' }
          ]
        }
      }
    },
    pain001: {
      name: 'pain.001.001.09',
      title: 'Customer Credit Transfer Initiation (Corporate ERP to Bank)',
      sender: 'Corporate Treasury System',
      receiver: 'Originating Bank (Debtor Agent)',
      elements: {
        grpHdr: {
          tag: '<GrpHdr>',
          fields: [
            { name: 'MsgId', value: 'SAP-PAYRUN-20260823-01', desc: 'Batch payment run ID generated by SAP / Oracle ERP.' },
            { name: 'CreDtTm', value: '2026-08-23T09:00:00Z', desc: 'Timestamp of corporate payroll dispatch.' },
            { name: 'InitgPty', value: 'Enterprise Global Corp', desc: 'Initiating party corporate legal name.' }
          ]
        },
        txInf: {
          tag: '<PmtInf>',
          fields: [
            { name: 'PmtInfId', value: 'PAYROLL-BATCH-001', desc: 'Payment Information block identifier.' },
            { name: 'PmtMtd', value: 'TRF (Credit Transfer)', desc: 'Initiation payment method indicator.' },
            { name: 'ReqdExctnDt', value: '2026-08-24', desc: 'Requested bank execution value date.' }
          ]
        },
        parties: {
          tag: '<Dbtr> & <DbtrAcct>',
          fields: [
            { name: 'DbtrAcct / IBAN', value: 'AU29ANZB0123456789', desc: 'Authoritative funding account at originating bank.' },
            { name: 'DbtrAgt / BIC', value: 'ANZBAU3MXXX', desc: 'Corporate relationship bank.' }
          ]
        },
        rmtInf: {
          tag: '<RmtInf>',
          fields: [
            { name: 'Strd / TaxRmt', value: 'Superannuation / PAYG withholding lines', desc: 'Automated payroll tax reconciliation metadata.' }
          ]
        }
      }
    },
    pacs002: {
      name: 'pacs.002.001.10',
      title: 'Payment Status Report (Real-Time ACK / NACK)',
      sender: 'Clearing House / Creditor Bank',
      receiver: 'Debtor Bank / Originator',
      elements: {
        grpHdr: {
          tag: '<GrpHdr>',
          fields: [
            { name: 'MsgId', value: 'PSR-20260823-99124', desc: 'Unique status notification message identifier.' }
          ]
        },
        txInf: {
          tag: '<TxInfAndSts>',
          fields: [
            { name: 'OrgnlEndToEndId', value: 'E2E-INV-2026-8849', desc: 'Reference linking back to original pacs.008 transfer.' },
            { name: 'TxSts', value: 'ACTC (Accepted Technical) / ACSC (Settled)', desc: 'Clearing status disposition.' }
          ]
        },
        parties: {
          tag: '<InstgAgt> & <InstdAgt>',
          fields: [
            { name: 'InstgAgt', value: 'NPP Clearing Hub (AU.NPP)', desc: 'Reporting infrastructure agent.' },
            { name: 'InstdAgt', value: 'BICFI: ANZBAU3MXXX', desc: 'Target recipient of settlement status.' }
          ]
        },
        rmtInf: {
          tag: '<StsRsnInf>',
          fields: [
            { name: 'Rsn / Cd', value: 'NARR (Settlement Successful)', desc: 'Standardized clearing reason code.' }
          ]
        }
      }
    },
    camt054: {
      name: 'camt.054.001.08',
      title: 'Bank-to-Customer Debit/Credit Notification (Real-Time Push)',
      sender: 'Creditor Bank (Bank B)',
      receiver: 'Beneficiary Customer (Creditor ERP / App)',
      elements: {
        grpHdr: {
          tag: '<GrpHdr>',
          fields: [
            { name: 'MsgId', value: 'CAMT054-20260823-771', desc: 'Unique push advice message ID.' }
          ]
        },
        txInf: {
          tag: '<Ntfctn / Ntry>',
          fields: [
            { name: 'Amt', value: 'AUD 12,450.00 CRDT', desc: 'Credited ledger entry amount.' },
            { name: 'Sts', value: 'BOOK (Booked)', desc: 'Core ledger posting status.' }
          ]
        },
        parties: {
          tag: '<Acct>',
          fields: [
            { name: 'Acct / Id', value: 'AU44WPAC9876543210', desc: 'Beneficiary account credited.' }
          ]
        },
        rmtInf: {
          tag: '<NtryDtls>',
          fields: [
            { name: 'Btch / NbOfTxs', value: '1', desc: 'Single entry real-time push notification.' }
          ]
        }
      }
    }
  };

  const curr = messages[selectedMsg];
  const currBlock = curr.elements[selectedBlock] || curr.elements.grpHdr;

  return (
    <div className="interactive-diagram-container" style={{ fontFamily: 'var(--ifm-font-family-base)' }}>
      {/* Header Bar */}
      <div className="interactive-diagram-header">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#fbbf24" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <polyline points="16 18 22 12 16 6" />
          <polyline points="8 6 2 12 8 18" />
        </svg>
        <span style={{ color: 'var(--ifm-color-content)', fontWeight: 700, fontSize: '15px' }}>
          ISO 20022 Message Flow & Schema Explorer: {curr.name}
        </span>
        <div style={{ marginLeft: 'auto', display: 'flex', gap: '6px' }}>
          {(['pacs008', 'pain001', 'pacs002', 'camt054'] as const).map((msgKey) => (
            <button
              key={msgKey}
              onClick={() => { setSelectedMsg(msgKey); setSelectedBlock('grpHdr'); }}
              style={{
                padding: '4px 8px',
                borderRadius: '6px',
                fontSize: '11px',
                fontWeight: 700,
                cursor: 'pointer',
                border: selectedMsg === msgKey ? '1px solid #fbbf24' : '1px solid transparent',
                background: selectedMsg === msgKey ? '#fbbf2418' : 'transparent',
                color: selectedMsg === msgKey ? '#fbbf24' : 'var(--ifm-color-content-secondary)'
              }}
            >
              {msgKey}
            </button>
          ))}
        </div>
      </div>

      <div style={{ padding: '16px' }}>
        <div style={{ marginBottom: '12px' }}>
          <div style={{ fontSize: '13px', fontWeight: 700, color: '#fbbf24' }}>{curr.title}</div>
          <div style={{ fontSize: '11px', color: 'var(--ifm-color-content-secondary)' }}>
            <strong>Sender:</strong> {curr.sender} &rarr; <strong>Receiver:</strong> {curr.receiver}
          </div>
        </div>

        {/* SVG Flow Canvas with Moving Arrows */}
        <div className="interactive-diagram-svg-wrapper interactive-diagram-grid-bg" style={{ borderRadius: '10px', marginBottom: '14px', overflow: 'hidden' }}>
          <svg viewBox="0 0 680 140" style={{ width: '100%', height: 'auto', display: 'block' }}>
            <defs>
              <marker id="iso-arr-amber" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto">
                <path d="M0,0 L0,6 L8,3 z" fill="#fbbf24" />
              </marker>
              <marker id="iso-arr-green" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto">
                <path d="M0,0 L0,6 L8,3 z" fill="#34d399" />
              </marker>
              <marker id="iso-arr-blue" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto">
                <path d="M0,0 L0,6 L8,3 z" fill="#38bdf8" />
              </marker>
            </defs>

            {/* Left Box: Sender Node */}
            <rect x="25" y="40" width="160" height="60" rx="8" fill="rgba(56,189,248,0.12)" stroke="#38bdf8" strokeWidth="1.5" />
            <text x="105" y="65" textAnchor="middle" fill="#38bdf8" fontSize="11" fontWeight="700">Originator / Sender</text>
            <text x="105" y="82" textAnchor="middle" fill="var(--ifm-color-content-secondary)" fontSize="9">
              {selectedMsg === 'pain001' ? 'Corporate ERP' : selectedMsg === 'pacs008' ? 'Debtor Bank (Bank A)' : selectedMsg === 'pacs002' ? 'Clearing / Creditor' : 'Creditor Bank (Bank B)'}
            </text>

            {/* Moving Arrow Conduit */}
            <line x1="185" y1="70" x2="265" y2="70" stroke="rgba(251,191,36,0.3)" strokeWidth="2" />
            <line x1="185" y1="70" x2="265" y2="70" stroke="#fbbf24" strokeWidth="2" strokeDasharray="6 4" className="interactive-diagram-flowing-path" markerEnd="url(#iso-arr-amber)" />

            {/* Center Box: ISO Message Package */}
            <rect x="270" y="30" width="140" height="80" rx="10" fill="rgba(251,191,36,0.12)" stroke="#fbbf24" strokeWidth="2" />
            <text x="340" y="55" textAnchor="middle" fill="#fbbf24" fontSize="12" fontWeight="800">{curr.name}</text>
            <text x="340" y="73" textAnchor="middle" fill="#34d399" fontSize="9.5" fontWeight="700">ISO 20022 XML</text>
            <text x="340" y="91" textAnchor="middle" fill="var(--ifm-color-content-secondary)" fontSize="8.5">Rich Remittance & LEI</text>

            {/* Moving Arrow Conduit 2 */}
            <line x1="410" y1="70" x2="490" y2="70" stroke="rgba(52,211,153,0.3)" strokeWidth="2" />
            <line x1="410" y1="70" x2="490" y2="70" stroke="#34d399" strokeWidth="2" strokeDasharray="6 4" className="interactive-diagram-flowing-path" markerEnd="url(#iso-arr-green)" />

            {/* Right Box: Receiver Node */}
            <rect x="495" y="40" width="160" height="60" rx="8" fill="rgba(52,211,153,0.12)" stroke="#34d399" strokeWidth="1.5" />
            <text x="575" y="65" textAnchor="middle" fill="#34d399" fontSize="11" fontWeight="700">Recipient / Clearing</text>
            <text x="575" y="82" textAnchor="middle" fill="var(--ifm-color-content-secondary)" fontSize="9">
              {selectedMsg === 'pain001' ? 'Originating Bank' : selectedMsg === 'pacs008' ? 'Creditor Bank (Bank B)' : selectedMsg === 'pacs002' ? 'Debtor Bank (ACK/NACK)' : 'Corporate Beneficiary'}
            </text>
          </svg>
        </div>

        {/* Section Selector Tabs */}
        <div style={{ display: 'flex', gap: '6px', marginBottom: '12px' }}>
          <button
            onClick={() => setSelectedBlock('grpHdr')}
            style={{
              padding: '6px 10px',
              borderRadius: '6px',
              fontSize: '11px',
              fontWeight: 700,
              cursor: 'pointer',
              border: selectedBlock === 'grpHdr' ? '1px solid #38bdf8' : '1px solid rgba(255,255,255,0.06)',
              background: selectedBlock === 'grpHdr' ? '#38bdf818' : '#090b14',
              color: selectedBlock === 'grpHdr' ? '#38bdf8' : 'var(--ifm-color-content-secondary)'
            }}
          >
            Group Header &lt;GrpHdr&gt;
          </button>
          <button
            onClick={() => setSelectedBlock('txInf')}
            style={{
              padding: '6px 10px',
              borderRadius: '6px',
              fontSize: '11px',
              fontWeight: 700,
              cursor: 'pointer',
              border: selectedBlock === 'txInf' ? '1px solid #34d399' : '1px solid rgba(255,255,255,0.06)',
              background: selectedBlock === 'txInf' ? '#34d39918' : '#090b14',
              color: selectedBlock === 'txInf' ? '#34d399' : 'var(--ifm-color-content-secondary)'
            }}
          >
            Transaction Info
          </button>
          <button
            onClick={() => setSelectedBlock('parties')}
            style={{
              padding: '6px 10px',
              borderRadius: '6px',
              fontSize: '11px',
              fontWeight: 700,
              cursor: 'pointer',
              border: selectedBlock === 'parties' ? '1px solid #a78bfa' : '1px solid rgba(255,255,255,0.06)',
              background: selectedBlock === 'parties' ? '#a78bfa18' : '#090b14',
              color: selectedBlock === 'parties' ? '#a78bfa' : 'var(--ifm-color-content-secondary)'
            }}
          >
            Parties &amp; Agents
          </button>
          <button
            onClick={() => setSelectedBlock('rmtInf')}
            style={{
              padding: '6px 10px',
              borderRadius: '6px',
              fontSize: '11px',
              fontWeight: 700,
              cursor: 'pointer',
              border: selectedBlock === 'rmtInf' ? '1px solid #f472b6' : '1px solid rgba(255,255,255,0.06)',
              background: selectedBlock === 'rmtInf' ? '#f472b618' : '#090b14',
              color: selectedBlock === 'rmtInf' ? '#f472b6' : 'var(--ifm-color-content-secondary)'
            }}
          >
            Remittance Data &lt;RmtInf&gt;
          </button>
        </div>

        {/* Selected XML Block Fields */}
        <div style={{
          background: '#0c0e17',
          borderRadius: '10px',
          border: '1px solid rgba(255,255,255,0.08)',
          padding: '14px'
        }}>
          <div style={{ fontSize: '12px', fontWeight: 700, color: '#fbbf24', marginBottom: '10px', fontFamily: 'monospace' }}>
            {currBlock.tag} Block Elements
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '8px' }}>
            {currBlock.fields.map((field) => (
              <div
                key={field.name}
                style={{
                  background: '#090b14',
                  padding: '10px',
                  borderRadius: '6px',
                  border: '1px solid rgba(255,255,255,0.05)'
                }}
              >
                <div style={{ fontSize: '11px', fontWeight: 700, color: '#38bdf8', fontFamily: 'monospace' }}>
                  {field.name}
                </div>
                <div style={{ fontSize: '11px', color: '#34d399', fontFamily: 'monospace', margin: '4px 0' }}>
                  {field.value}
                </div>
                <div style={{ fontSize: '10.5px', color: 'var(--ifm-color-content-secondary)', lineHeight: 1.4 }}>
                  {field.desc}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
