import React, { useState } from 'react';

export default function Iso20022MessageInspectorDiagram({ initialMsg = 'pacs008' }: { initialMsg?: 'pacs008' | 'pain001' | 'pacs002' | 'camt054' }): React.JSX.Element {
  const [selectedMsg, setSelectedMsg] = useState<'pacs008' | 'pain001' | 'pacs002' | 'camt054'>(initialMsg);
  const [selectedBlock, setSelectedBlock] = useState<'grpHdr' | 'txInf' | 'parties' | 'rmtInf'>('grpHdr');

  const messages = {
    pacs008: {
      name: 'pacs.008.001.08',
      title: 'Financial Institutional Customer Credit Transfer (A2A Clearing)',
      sender: 'Debtor Agent (Bank A)',
      receiver: 'Creditor Agent (Bank B) via Clearing (NPP/RTGS/SWIFT)',
      elements: {
        grpHdr: {
          tag: '<GrpHdr>',
          fields: [
            { name: 'MsgId', value: 'AU20260823NPP00123984', desc: 'Globally unique message identifier assigned by sender.' },
            { name: 'CreDtTm', value: '2026-08-23T14:30:00.120Z', desc: 'Exact creation timestamp in UTC format.' },
            { name: 'NbOfTxs', value: '1', desc: 'Number of individual transaction blocks in this message bundle.' },
            { name: 'SttlmInf', value: 'SttlmMtd = CLRG / ClrSys = AU.NPP', desc: 'Settlement Method: Instant settlement via NPP Clearing System.' }
          ]
        },
        txInf: {
          tag: '<CdtTrfTxInf>',
          fields: [
            { name: 'PmtId / EndToEndId', value: 'E2E-INV-2026-8849', desc: 'Immutable end-to-end reconciliation reference passed to creditor.' },
            { name: 'PmtId / UETR', value: 'c81b0e3e-63f2-4e92-9118-e21a2a9042b1', desc: 'SWIFT Universal End-to-End Tracking Reference (UUID v4).' },
            { name: 'IntrBkSttlmAmt', value: 'AUD 12,450.00', desc: 'Interbank settlement amount and ISO 4217 currency code.' },
            { name: 'ChrgBr', value: 'SLEV / SHAR', desc: 'Charge Bearer rule governing intermediary fee distribution.' }
          ]
        },
        parties: {
          tag: '<Dbtr> & <Cdtr>',
          fields: [
            { name: 'Dbtr (Debtor)', value: 'Acme Corp Pty Ltd (LEI: 5493006MHB84DD0Z7432)', desc: 'Originating payer legal entity identifier and name.' },
            { name: 'DbtrAgt (Bank A)', value: 'BICFI: ANZBAU3MXXX', desc: 'Debtor institution Business Identifier Code.' },
            { name: 'CdtrAgt (Bank B)', value: 'BICFI: WPACAU2SXXX', desc: 'Creditor institution Business Identifier Code.' },
            { name: 'Cdtr (Creditor)', value: 'Apex Logistics Global Pty Ltd', desc: 'Final beneficiary account owner.' }
          ]
        },
        rmtInf: {
          tag: '<RmtInf>',
          fields: [
            { name: 'Ustrd (Unstructured)', value: 'Invoice 8849 Supplier Payment August', desc: 'Free text narrative displayed on bank statements.' },
            { name: 'Strd / RfrdDocInf', value: 'Type: CINV / Nb: 8849 / RltdDt: 2026-08-20', desc: 'Structured Commercial Invoice metadata enabling automated ERP matching.' }
          ]
        }
      }
    },
    pain001: {
      name: 'pain.001.001.09',
      title: 'Customer Credit Transfer Initiation (Corporate ERP to Bank)',
      sender: 'Corporate Treasury System',
      receiver: 'Originating Bank (Debtor Agent)',
      elements: {
        grpHdr: {
          tag: '<GrpHdr>',
          fields: [
            { name: 'MsgId', value: 'SAP-PAYRUN-20260823-01', desc: 'Batch payment run ID generated by SAP / Oracle ERP.' },
            { name: 'CreDtTm', value: '2026-08-23T09:00:00Z', desc: 'Timestamp of corporate payroll dispatch.' },
            { name: 'InitgPty', value: 'Enterprise Global Corp', desc: 'Initiating party corporate legal name.' }
          ]
        },
        txInf: {
          tag: '<PmtInf>',
          fields: [
            { name: 'PmtInfId', value: 'PAYROLL-BATCH-001', desc: 'Payment Information block identifier.' },
            { name: 'PmtMtd', value: 'TRF (Credit Transfer)', desc: 'Initiation payment method indicator.' },
            { name: 'ReqdExctnDt', value: '2026-08-24', desc: 'Requested bank execution value date.' }
          ]
        },
        parties: {
          tag: '<Dbtr> & <DbtrAcct>',
          fields: [
            { name: 'DbtrAcct / IBAN', value: 'AU29ANZB0123456789', desc: 'Authoritative funding account at originating bank.' },
            { name: 'DbtrAgt / BIC', value: 'ANZBAU3MXXX', desc: 'Corporate relationship bank.' }
          ]
        },
        rmtInf: {
          tag: '<RmtInf>',
          fields: [
            { name: 'Strd / TaxRmt', value: 'Superannuation / PAYG withholding lines', desc: 'Automated payroll tax reconciliation metadata.' }
          ]
        }
      }
    },
    pacs002: {
      name: 'pacs.002.001.10',
      title: 'Payment Status Report (Real-Time ACK / NACK)',
      sender: 'Clearing House / Creditor Bank',
      receiver: 'Debtor Bank / Originator',
      elements: {
        grpHdr: {
          tag: '<GrpHdr>',
          fields: [
            { name: 'MsgId', value: 'PSR-20260823-99124', desc: 'Unique status notification message identifier.' }
          ]
        },
        txInf: {
          tag: '<TxInfAndSts>',
          fields: [
            { name: 'TxSts', value: 'ACCP (Accepted) / RJCT (Rejected)', desc: 'Final clearing disposition status.' },
            { name: 'StsRsnInf / Cd', value: 'AC01 / AG01 / AM04', desc: 'Standard ISO reason code (e.g. Incorrect Account / Transaction Forbidden).' }
          ]
        },
        parties: {
          tag: '<InstgAgt>',
          fields: [
            { name: 'InstgAgt', value: 'NPP Clearing Hub (RBA)', desc: 'Issuing settlement authority.' }
          ]
        },
        rmtInf: {
          tag: '<OrgnlTxRef>',
          fields: [
            { name: 'OrgnlEndToEndId', value: 'E2E-INV-2026-8849', desc: 'Matches original transaction EndToEndId.' }
          ]
        }
      }
    },
    camt054: {
      name: 'camt.054.001.08',
      title: 'Bank-to-Customer Debit/Credit Notification',
      sender: 'Bank',
      receiver: 'Corporate Customer ERP',
      elements: {
        grpHdr: {
          tag: '<GrpHdr>',
          fields: [
            { name: 'MsgId', value: 'NOTIF-20260823-4412', desc: 'Real-time ledger posting confirmation.' }
          ]
        },
        txInf: {
          tag: '<Ntfctn / Ntry>',
          fields: [
            { name: 'Amt', value: 'AUD 12,450.00 CRDT', desc: 'Credited ledger entry amount.' },
            { name: 'Sts', value: 'BOOK (Booked)', desc: 'Core ledger posting status.' }
          ]
        },
        parties: {
          tag: '<Acct>',
          fields: [
            { name: 'Acct / Id', value: 'AU44WPAC9876543210', desc: 'Beneficiary account credited.' }
          ]
        },
        rmtInf: {
          tag: '<NtryDtls>',
          fields: [
            { name: 'Btch / NbOfTxs', value: '1', desc: 'Single entry real-time push notification.' }
          ]
        }
      }
    }
  };

  const curr = messages[selectedMsg];
  const currBlock = curr.elements[selectedBlock] || curr.elements.grpHdr;

  return (
    <div className="interactive-diagram-container" style={{ fontFamily: 'var(--ifm-font-family-base)' }}>
      {/* Header Bar */}
      <div className="interactive-diagram-header">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#fbbf24" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <polyline points="16 18 22 12 16 6" />
          <polyline points="8 6 2 12 8 18" />
        </svg>
        <span style={{ color: 'var(--ifm-color-content)', fontWeight: 700, fontSize: '15px' }}>
          ISO 20022 Universal Message Inspector: {curr.name}
        </span>
        <div style={{ marginLeft: 'auto', display: 'flex', gap: '6px' }}>
          {(['pacs008', 'pain001', 'pacs002', 'camt054'] as const).map((msgKey) => (
            <button
              key={msgKey}
              onClick={() => { setSelectedMsg(msgKey); setSelectedBlock('grpHdr'); }}
              style={{
                padding: '4px 8px',
                borderRadius: '6px',
                fontSize: '11px',
                fontWeight: 700,
                cursor: 'pointer',
                border: selectedMsg === msgKey ? '1px solid #fbbf24' : '1px solid transparent',
                background: selectedMsg === msgKey ? '#fbbf2418' : 'transparent',
                color: selectedMsg === msgKey ? '#fbbf24' : 'var(--ifm-color-content-secondary)'
              }}
            >
              {msgKey}
            </button>
          ))}
        </div>
      </div>

      <div style={{ padding: '16px' }}>
        <div style={{ marginBottom: '12px' }}>
          <div style={{ fontSize: '13px', fontWeight: 700, color: '#fbbf24' }}>{curr.title}</div>
          <div style={{ fontSize: '11px', color: 'var(--ifm-color-content-secondary)' }}>
            <strong>Sender:</strong> {curr.sender} &rarr; <strong>Receiver:</strong> {curr.receiver}
          </div>
        </div>

        {/* Section Selector Tabs */}
        <div style={{ display: 'flex', gap: '6px', marginBottom: '12px' }}>
          <button
            onClick={() => setSelectedBlock('grpHdr')}
            style={{
              padding: '6px 10px',
              borderRadius: '6px',
              fontSize: '11px',
              fontWeight: 700,
              cursor: 'pointer',
              border: selectedBlock === 'grpHdr' ? '1px solid #38bdf8' : '1px solid rgba(255,255,255,0.06)',
              background: selectedBlock === 'grpHdr' ? '#38bdf818' : '#090b14',
              color: selectedBlock === 'grpHdr' ? '#38bdf8' : 'var(--ifm-color-content-secondary)'
            }}
          >
            Group Header &lt;GrpHdr&gt;
          </button>
          <button
            onClick={() => setSelectedBlock('txInf')}
            style={{
              padding: '6px 10px',
              borderRadius: '6px',
              fontSize: '11px',
              fontWeight: 700,
              cursor: 'pointer',
              border: selectedBlock === 'txInf' ? '1px solid #34d399' : '1px solid rgba(255,255,255,0.06)',
              background: selectedBlock === 'txInf' ? '#34d39918' : '#090b14',
              color: selectedBlock === 'txInf' ? '#34d399' : 'var(--ifm-color-content-secondary)'
            }}
          >
            Transaction Info
          </button>
          <button
            onClick={() => setSelectedBlock('parties')}
            style={{
              padding: '6px 10px',
              borderRadius: '6px',
              fontSize: '11px',
              fontWeight: 700,
              cursor: 'pointer',
              border: selectedBlock === 'parties' ? '1px solid #a78bfa' : '1px solid rgba(255,255,255,0.06)',
              background: selectedBlock === 'parties' ? '#a78bfa18' : '#090b14',
              color: selectedBlock === 'parties' ? '#a78bfa' : 'var(--ifm-color-content-secondary)'
            }}
          >
            Parties &amp; Agents
          </button>
          <button
            onClick={() => setSelectedBlock('rmtInf')}
            style={{
              padding: '6px 10px',
              borderRadius: '6px',
              fontSize: '11px',
              fontWeight: 700,
              cursor: 'pointer',
              border: selectedBlock === 'rmtInf' ? '1px solid #f472b6' : '1px solid rgba(255,255,255,0.06)',
              background: selectedBlock === 'rmtInf' ? '#f472b618' : '#090b14',
              color: selectedBlock === 'rmtInf' ? '#f472b6' : 'var(--ifm-color-content-secondary)'
            }}
          >
            Remittance Data &lt;RmtInf&gt;
          </button>
        </div>

        {/* Selected XML Block Fields */}
        <div style={{
          background: '#0c0e17',
          borderRadius: '10px',
          border: '1px solid rgba(255,255,255,0.08)',
          padding: '14px'
        }}>
          <div style={{ fontSize: '12px', fontWeight: 700, color: '#fbbf24', marginBottom: '10px', fontFamily: 'monospace' }}>
            {currBlock.tag} Block Elements
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '8px' }}>
            {currBlock.fields.map((field) => (
              <div
                key={field.name}
                style={{
                  background: '#090b14',
                  padding: '10px',
                  borderRadius: '6px',
                  border: '1px solid rgba(255,255,255,0.05)'
                }}
              >
                <div style={{ fontSize: '11px', fontWeight: 700, color: '#38bdf8', fontFamily: 'monospace' }}>
                  {field.name}
                </div>
                <div style={{ fontSize: '11px', color: '#34d399', fontFamily: 'monospace', margin: '4px 0' }}>
                  {field.value}
                </div>
                <div style={{ fontSize: '10.5px', color: 'var(--ifm-color-content-secondary)', lineHeight: 1.4 }}>
                  {field.desc}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
