import React, { useState } from 'react';

type Section = 'header' | 'key' | 'iv' | 'ciphertext' | 'tag';

export default function JweAnatomyDiagram(): React.JSX.Element {
  const [activeSection, setActiveSection] = useState<Section>('header');

  const content = {
    header: {
      raw: 'eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2R0NNIn0',
      decoded: `{
  "alg": "RSA-OAEP-256",
  "enc": "A256GCM",
  "kid": "key-2024-01"
}`,
      desc: 'The JWE Protected Header defines the algorithms used. "alg" is the asymmetric key wrap algorithm (RSA-OAEP-256) used to encrypt the content encryption key (CEK). "enc" is the symmetric encryption method (AES-256-GCM) used to encrypt the payload.'
    },
    key: {
      raw: 'OK36q8z4Q...[RSA Encrypted Key]',
      decoded: 'Contains the symmetric Content Encryption Key (CEK), which is generated on the fly and encrypted with the recipient\'s RSA public key.',
      desc: 'The Encrypted Key contains the symmetric AES key (CEK) that actually encrypted the payload. Because the CEK is wrapped using the server\'s public RSA key, only the server (which holds the private RSA key) can decrypt and retrieve it.'
    },
    iv: {
      raw: 'AxY8zGN_A...[96-bit random nonce]',
      decoded: 'Initialization Vector (IV) - random bytes to guarantee cryptographic uniqueness.',
      desc: 'The Initialization Vector (IV) is a random nonce generated for the AES-GCM operation. This ensures that encrypting the same message twice yields entirely different ciphertexts.'
    },
    ciphertext: {
      raw: 'q0Y8mG1z...[AES-GCM encrypted payload]',
      decoded: 'Plaintext data encrypted using the CEK under AES-256-GCM.',
      desc: 'The Ciphertext is the actual encrypted data/payload (e.g. JWT claims or raw JSON request). It is completely unreadable without the symmetric CEK.'
    },
    tag: {
      raw: '7vA8zL9P...[128-bit integrity tag]',
      decoded: 'Authentication Tag - validates ciphertext and header integrity.',
      desc: 'The Authentication Tag is a cryptographic checksum generated by the AEAD cipher (AES-GCM). It prevents tampering, ensuring that if any bit of the ciphertext or header is modified in transit, decryption will fail.'
    }
  };

  return (
    <div className="interactive-diagram-container" style={{ margin: '1.5rem 0' }}>
      <div className="interactive-diagram-card-header" style={{ padding: '0.6rem 1rem', borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
        <h3 style={{ margin: 0, fontSize: '0.95rem', fontWeight: 700 }}>
          📦 Interactive JWE (JSON Web Encryption) Anatomy
        </h3>
      </div>

      <div style={{ padding: '1.2rem' }} className="interactive-diagram-grid-bg">
        {/* Token representation */}
        <div style={{ background: '#090b14', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 6, padding: '10px 14px', fontFamily: 'monospace', fontSize: '0.8rem', wordBreak: 'break-all', lineHeight: 1.6, marginBottom: '1.2rem' }}>
          <span onMouseEnter={() => setActiveSection('header')} style={{ color: '#38bdf8', cursor: 'pointer', background: activeSection === 'header' ? 'rgba(56,189,248,0.15)' : 'transparent', padding: '2px 4px', borderRadius: 3, fontWeight: 700 }}>
            {content.header.raw}
          </span>
          <span style={{ color: '#94a3b8' }}>.</span>
          <span onMouseEnter={() => setActiveSection('key')} style={{ color: '#a78bfa', cursor: 'pointer', background: activeSection === 'key' ? 'rgba(167,139,250,0.15)' : 'transparent', padding: '2px 4px', borderRadius: 3, fontWeight: 700 }}>
            {content.key.raw}
          </span>
          <span style={{ color: '#94a3b8' }}>.</span>
          <span onMouseEnter={() => setActiveSection('iv')} style={{ color: '#fb923c', cursor: 'pointer', background: activeSection === 'iv' ? 'rgba(251,146,60,0.15)' : 'transparent', padding: '2px 4px', borderRadius: 3, fontWeight: 700 }}>
            {content.iv.raw}
          </span>
          <span style={{ color: '#94a3b8' }}>.</span>
          <span onMouseEnter={() => setActiveSection('ciphertext')} style={{ color: '#4ade80', cursor: 'pointer', background: activeSection === 'ciphertext' ? 'rgba(74,222,128,0.15)' : 'transparent', padding: '2px 4px', borderRadius: 3, fontWeight: 700 }}>
            {content.ciphertext.raw}
          </span>
          <span style={{ color: '#94a3b8' }}>.</span>
          <span onMouseEnter={() => setActiveSection('tag')} style={{ color: '#f87171', cursor: 'pointer', background: activeSection === 'tag' ? 'rgba(248,113,113,0.15)' : 'transparent', padding: '2px 4px', borderRadius: 3, fontWeight: 700 }}>
            {content.tag.raw}
          </span>
        </div>

        {/* Decoder split view */}
        <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 1fr', gap: '1rem' }}>
          {/* Explanation */}
          <div style={{ background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 8, padding: '1rem' }}>
            <h4 style={{ margin: '0 0 8px 0', fontSize: '0.85rem', textTransform: 'capitalize', color: activeSection === 'header' ? '#38bdf8' : activeSection === 'key' ? '#a78bfa' : activeSection === 'iv' ? '#fb923c' : activeSection === 'ciphertext' ? '#4ade80' : '#f87171' }}>
              JWE Part {activeSection === 'header' ? '1: Header' : activeSection === 'key' ? '2: Encrypted Key' : activeSection === 'iv' ? '3: IV' : activeSection === 'ciphertext' ? '4: Ciphertext' : '5: Auth Tag'}
            </h4>
            <p style={{ margin: 0, fontSize: '0.78rem', color: '#94a3b8', lineHeight: 1.5 }}>
              {content[activeSection].desc}
            </p>
          </div>

          {/* Value panel */}
          <div style={{ background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 8, padding: '1rem' }}>
            <h4 style={{ margin: '0 0 8px 0', fontSize: '0.85rem', color: '#e2e8f0' }}>Parsed / Value</h4>
            <pre style={{ margin: 0, padding: '8px 12px', background: '#090b14', border: '1px solid rgba(255,255,255,0.05)', borderRadius: 4, fontFamily: 'monospace', fontSize: '0.72rem', color: '#e2e8f0', overflowX: 'auto', whiteSpace: 'pre-wrap' }}>
              {content[activeSection].decoded}
            </pre>
          </div>
        </div>
      </div>
      <p className="interactive-diagram-helper-text">💡 Hover over each of the 5 segments of the JWE string to decode them.</p>
    </div>
  );
}
