import React, { useState, useEffect } from 'react';

interface Stage {
  id: string;
  number: number;
  title: string;
  role: string;
  color: string;
  icon: string;
  summary: string;
  actions: string[];
  tips: string;
}

const STAGES: Stage[] = [
  {
    id: 'plan',
    number: 1,
    title: 'Plan & Specify',
    role: 'The Architect',
    color: '#38bdf8', // Sky Blue
    icon: 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01',
    summary: 'Write structural specs, implementation plans, API schemas, and tech constraints before launching the coding agent.',
    actions: [
      'Define clear tech stack, versions, and architectural rules in AGENTS.md',
      'Create a step-by-step implementation plan in a temporary scratch markdown file',
      'Establish API schemas, data structures, and edge-case boundaries upfront',
      'Limit scope per prompt: don’t ask the agent to build the whole app at once'
    ],
    tips: 'A 5-minute planning phase prevents hours of untangling spaghetti code generated by context-blind agents.'
  },
  {
    id: 'guide',
    number: 2,
    title: 'Guide & Implement',
    role: 'The Director',
    color: '#a78bfa', // Purple
    icon: 'M13 10V3L4 14h7v7l9-11h-7z',
    summary: 'Iteratively steer the agent task-by-task. Feed compiler errors and log traces directly back to the context.',
    actions: [
      'Execute one single task from your plan at a time',
      'Feed compiler errors and stack traces directly into chat context',
      'Steer immediately if the agent takes the wrong path (e.g. "Do not use reflection")',
      'Keep files small and modular (SRP) so the agent maintains context easily'
    ],
    tips: 'If the agent gets stuck in an infinite loop, stop it, locate the root cause yourself, and provide a scoped constraint.'
  },
  {
    id: 'verify',
    number: 3,
    title: 'Verify & Review',
    role: 'The QA & Reviewer',
    color: '#fbbf24', // Amber
    icon: 'M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z',
    summary: 'Inspect every line in git diffs, run linter and compiler checks, and execute automated test suites.',
    actions: [
      'Inspect line-by-line Git diffs before clicking Accept',
      'Run build scripts (`npm run build` or `./gradlew build`) to catch compile bugs',
      'Execute automated test suites (`npm test`) to prevent regression issues',
      'Check for security vulnerabilities, hardcoded secrets, or unneeded package dependencies'
    ],
    tips: 'Never accept code blindly. Ghost coding is the #1 cause of unmaintainable technical debt.'
  }
];

export default function VibeCodingWorkflowDiagram() {
  const [activeStageId, setActiveStageId] = useState<string>('plan');
  const [decision, setDecision] = useState<'bugs' | 'ship' | null>(null);
  const [isPlaying, setIsPlaying] = useState<boolean>(false);

  const activeStage = STAGES.find(s => s.id === activeStageId) || STAGES[0];

  useEffect(() => {
    if (!isPlaying) return;

    const sequence = [
      { stage: 'plan', decision: null },
      { stage: 'guide', decision: null },
      { stage: 'verify', decision: null },
      { stage: 'verify', decision: 'bugs' },
      { stage: 'guide', decision: null },
      { stage: 'verify', decision: 'ship' }
    ];

    let step = 0;
    const interval = setInterval(() => {
      step = (step + 1) % sequence.length;
      setActiveStageId(sequence[step].stage);
      setDecision(sequence[step].decision as 'bugs' | 'ship' | null);
    }, 2400);

    return () => clearInterval(interval);
  }, [isPlaying]);

  return (
    <div className="interactive-diagram-container" style={{ fontFamily: 'var(--ifm-font-family-base)' }}>
      {/* Header Bar */}
      <div className="interactive-diagram-header">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#34d399" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z" />
        </svg>
        <span style={{ color: 'var(--ifm-color-content)', fontWeight: 600 }}>The Vibe Coding Lifecycle & Feedback Loop</span>
        
        <button
          onClick={() => setIsPlaying(!isPlaying)}
          style={{
            marginLeft: 'auto',
            background: isPlaying ? '#f8717118' : '#34d39918',
            border: `1px solid ${isPlaying ? '#f8717150' : '#34d39950'}`,
            color: isPlaying ? '#f87171' : '#34d399',
            padding: '4px 12px',
            borderRadius: '6px',
            fontSize: '12px',
            fontWeight: 600,
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: '6px'
          }}
        >
          {isPlaying ? (
            <>
              <svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor">
                <rect x="6" y="4" width="4" height="16" />
                <rect x="14" y="4" width="4" height="16" />
              </svg>
              Pause Flow
            </>
          ) : (
            <>
              <svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor">
                <polygon points="5 3 19 12 5 21 5 3" />
              </svg>
              Animate Lifecycle
            </>
          )}
        </button>
      </div>

      {/* Main Flow Grid */}
      <div style={{ padding: '20px', background: '#0d0f1e' }}>
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
          gap: '14px',
          alignItems: 'stretch'
        }}>
          {STAGES.map((stage) => {
            const isActive = activeStageId === stage.id && !decision;
            return (
              <div
                key={stage.id}
                onClick={() => {
                  setActiveStageId(stage.id);
                  setDecision(null);
                  setIsPlaying(false);
                }}
                style={{
                  background: isActive ? `${stage.color}15` : '#13162b',
                  border: `2px solid ${isActive ? stage.color : '#1e2342'}`,
                  borderRadius: '10px',
                  padding: '16px',
                  cursor: 'pointer',
                  transition: 'all 0.2s ease',
                  boxShadow: isActive ? `0 0 16px ${stage.color}30` : 'none',
                  position: 'relative'
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px' }}>
                  <div style={{
                    width: '28px',
                    height: '28px',
                    borderRadius: '50%',
                    background: stage.color,
                    color: '#090b14',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontWeight: 700,
                    fontSize: '14px'
                  }}>
                    {stage.number}
                  </div>
                  <div>
                    <div style={{ fontSize: '15px', fontWeight: 700, color: 'var(--ifm-color-content)' }}>{stage.title}</div>
                    <div style={{ fontSize: '11px', color: stage.color, fontWeight: 600 }}>{stage.role}</div>
                  </div>
                </div>

                <div style={{ fontSize: '12px', color: 'var(--ifm-color-content-secondary)', lineHeight: '1.4' }}>
                  {stage.summary}
                </div>

                {isActive && (
                  <div style={{
                    position: 'absolute',
                    bottom: '-8px',
                    left: '50%',
                    transform: 'translateX(-50%)',
                    width: '16px',
                    height: '16px',
                    background: stage.color,
                    clipPath: 'polygon(50% 100%, 0 0, 100% 0)'
                  }} />
                )}
              </div>
            );
          })}
        </div>

        {/* Branch / Loop Indicator Panel */}
        <div style={{
          marginTop: '20px',
          display: 'grid',
          gridTemplateColumns: '1fr 1fr',
          gap: '12px'
        }}>
          {/* Branch 1: Bugs Found -> Feedback Loop */}
          <div
            onClick={() => {
              setActiveStageId('guide');
              setDecision('bugs');
              setIsPlaying(false);
            }}
            style={{
              background: decision === 'bugs' ? '#f8717118' : '#13162b',
              border: `1.5px dashed ${decision === 'bugs' ? '#f87171' : '#f8717140'}`,
              borderRadius: '8px',
              padding: '12px 14px',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '12px',
              transition: 'all 0.2s ease'
            }}
          >
            <div style={{
              width: '32px',
              height: '32px',
              borderRadius: '6px',
              background: '#f8717120',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#f87171',
              flexShrink: 0
            }}>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" />
                <line x1="12" y1="9" x2="12" y2="13" />
                <line x1="12" y1="17" x2="12.01" y2="17" />
              </svg>
            </div>
            <div>
              <div style={{ fontSize: '13px', fontWeight: 700, color: '#f87171' }}>
                Bugs or Test Failures Found
              </div>
              <div style={{ fontSize: '11px', color: 'var(--ifm-color-content-secondary)' }}>
                ↺ Feedback loop back to Stage 2 (Guide & Implement with stacktrace context)
              </div>
            </div>
          </div>

          {/* Branch 2: Production Ready */}
          <div
            onClick={() => {
              setActiveStageId('verify');
              setDecision('ship');
              setIsPlaying(false);
            }}
            style={{
              background: decision === 'ship' ? '#34d39918' : '#13162b',
              border: `1.5px dashed ${decision === 'ship' ? '#34d399' : '#34d39940'}`,
              borderRadius: '8px',
              padding: '12px 14px',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '12px',
              transition: 'all 0.2s ease'
            }}
          >
            <div style={{
              width: '32px',
              height: '32px',
              borderRadius: '6px',
              background: '#34d39920',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#34d399',
              flexShrink: 0
            }}>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
                <polyline points="22 4 12 14.01 9 11.01" />
              </svg>
            </div>
            <div>
              <div style={{ fontSize: '13px', fontWeight: 700, color: '#34d399' }}>
                All Tests & Linters Pass
              </div>
              <div style={{ fontSize: '11px', color: 'var(--ifm-color-content-secondary)' }}>
                ✓ Code approved, diff merged & production ready
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Details Card */}
      <div className="interactive-diagram-details-card" style={{ borderTop: '1px solid #1e2342', padding: '18px 20px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '12px' }}>
          <div style={{
            width: '10px',
            height: '10px',
            borderRadius: '50%',
            background: decision === 'bugs' ? '#f87171' : decision === 'ship' ? '#34d399' : activeStage.color
          }} />
          <div style={{ fontSize: '15px', fontWeight: 700, color: 'var(--ifm-color-content)' }}>
            {decision === 'bugs' ? (
              <span>Iteration Loop: Feeding Stacktrace Context Back to Stage 2</span>
            ) : decision === 'ship' ? (
              <span>Production Ready: Verified & Merged</span>
            ) : (
              <span>Stage {activeStage.number}: {activeStage.title} ({activeStage.role})</span>
            )}
          </div>
        </div>

        {decision === 'bugs' ? (
          <div>
            <p style={{ fontSize: '13px', color: 'var(--ifm-color-content-secondary)', marginBottom: '10px' }}>
              When linting or automated tests fail, do NOT enter an infinite guessing loop. Copy the exact compiler error or test runner output and feed it back to the agent:
            </p>
            <div style={{
              background: '#090b14',
              padding: '12px',
              borderRadius: '6px',
              fontFamily: 'monospace',
              fontSize: '12px',
              color: '#f87171',
              border: '1px solid #f8717130'
            }}>
              "The build failed with: java.lang.NullPointerException at PaymentService.java:42. Inspect line 42 and add a null guard for recipientId."
            </div>
          </div>
        ) : decision === 'ship' ? (
          <div>
            <p style={{ fontSize: '13px', color: 'var(--ifm-color-content-secondary)', marginBottom: '10px' }}>
              Your feature has passed all automated tests, static analysis checks, and line-by-line diff review. Commit the changes and reset context before prompting the next feature!
            </p>
            <div style={{
              background: '#34d39910',
              padding: '10px 14px',
              borderRadius: '6px',
              fontSize: '12px',
              color: '#34d399',
              border: '1px solid #34d39930',
              fontWeight: 600
            }}>
              🚀 Tip: Run `/compact` or start a fresh session to maintain 100% token headroom for the next feature.
            </div>
          </div>
        ) : (
          <div>
            <div style={{ fontSize: '12px', fontWeight: 700, color: activeStage.color, textTransform: 'uppercase', tracking: '0.05em', marginBottom: '8px' }}>
              Core Action Plan
            </div>
            <ul style={{ paddingLeft: '18px', margin: '0 0 14px 0', fontSize: '13px', color: 'var(--ifm-color-content-secondary)' }}>
              {activeStage.actions.map((act, idx) => (
                <li key={idx} style={{ marginBottom: '6px' }}>{act}</li>
              ))}
            </ul>

            <div style={{
              background: '#13162b',
              padding: '10px 14px',
              borderRadius: '6px',
              borderLeft: `4px solid ${activeStage.color}`,
              fontSize: '12px',
              color: 'var(--ifm-color-content-secondary)'
            }}>
              <strong style={{ color: activeStage.color }}>Director Tip: </strong>
              {activeStage.tips}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
