import os
import re
import glob

def parse_sidebars(sidebars_path):
    with open(sidebars_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Extract all literal string values inside quotes
    explicit_ids = set()
    matches = re.findall(r"['\"]([^'\"]+?)['\"]", content)
    for m in matches:
        explicit_ids.add(m)

    # Extract autogenerated directories
    autogen_dirs = set()
    autogen_matches = re.findall(r"dirName\s*:\s*['\"]([^'\"]+?)['\"]", content)
    for m in autogen_matches:
        autogen_dirs.add(m)

    return explicit_ids, autogen_dirs

def get_docusaurus_id(filepath, docs_dir):
    rel_path = os.path.relpath(filepath, docs_dir)
    rel_dir = os.path.dirname(rel_path)
    base_name = os.path.basename(filepath)
    filename_without_ext = base_name[:-3]

    doc_id = filename_without_ext
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            fm_match = re.match(r'^---\s*\n(.*?)\n---\s*\n', content, re.DOTALL)
            if fm_match:
                fm_text = fm_match.group(1)
                id_match = re.search(r'^id\s*:\s*([^\n]+)', fm_text, re.MULTILINE)
                if id_match:
                    doc_id = id_match.group(1).strip()
    except Exception:
        pass

    if rel_dir and rel_dir != '.':
        return f"{rel_dir}/{doc_id}"
    return doc_id

def is_in_sidebar(doc_id, explicit_ids, autogen_dirs):
    if doc_id in explicit_ids:
        return True
    for autogen_dir in autogen_dirs:
        if doc_id.startswith(autogen_dir + '/'):
            return True
    return False

def main():
    workspace_dir = "/Users/lukhuong/Desktop/docusaurus-knowledge-base-template"
    docs_dir = os.path.join(workspace_dir, "docs")
    sidebars_path = os.path.join(workspace_dir, "sidebars.ts")

    explicit_ids, autogen_dirs = parse_sidebars(sidebars_path)
    print(f"Loaded {len(explicit_ids)} unique string tokens and {len(autogen_dirs)} autogenerated directories from sidebars.ts.\n")

    # Find all .md files recursively
    all_md_files = []
    for root, dirs, files in os.walk(docs_dir):
        for file in files:
            if file.endswith('.md'):
                all_md_files.append(os.path.join(root, file))

    print(f"Found {len(all_md_files)} markdown files under docs/.\n")

    missing_docs = []

    for filepath in sorted(all_md_files):
        rel_path = os.path.relpath(filepath, docs_dir)
        doc_id = get_docusaurus_id(filepath, docs_dir)

        if not is_in_sidebar(doc_id, explicit_ids, autogen_dirs):
            missing_docs.append((rel_path, doc_id))
            print(f"❌ Missing file: {rel_path} (ID: {doc_id})")

    print("\n--- Summary ---")
    print(f"Total missing markdown files: {len(missing_docs)}")

if __name__ == "__main__":
    main()
