# Junior Scenarios (Scenarios 14 to 38: 25 scenarios)

JUNIOR_SCENARIOS = [
  {
    "id": "implicit_type_cast_varchar_to_int",
    "title": "Implicit Type Coercion Disables Index Seek",
    "difficulty": "Junior",
    "category": "data_types",
    "categoryLabel": "Data Types & Type Coercion",
    "tableName": "customers",
    "rowCount": "8,000,000 rows",
    "tableSizeDisk": "2.1 GB on disk",
    "slowQuery": """SELECT customer_id, full_name, email, phone_number
FROM customers
WHERE phone_number = 14155552671;""",
    "initialCost": 215400,
    "initialLatencyMs": 2840,
    "initialPlanSummary": "Seq Scan on customers (cost=0.00..215400.00 rows=1) Filter: ((phone_number)::numeric = 14155552671::numeric)",
    "businessContext": "Customer support hotline lookup by phone number takes 3 seconds. Table has an index on phone_number (VARCHAR), but developers passed a raw integer in the ORM query.",
    "strategies": [
      {
        "id": "strat_cast_string_optimal",
        "title": "Query with String Literal Matching Column Type",
        "sqlCommand": "SELECT customer_id, full_name, email, phone_number FROM customers WHERE phone_number = '14155552671';",
        "isOptimal": True,
        "resultingCost": 4.2,
        "resultingLatencyMs": 0.8,
        "executionPlanSummary": "Index Scan using idx_customers_phone (cost=0.43..4.20 rows=1) -> Exact B-Tree Seek",
        "engineExplanation": "Winner! By matching the VARCHAR column type with a string literal '14155552671', the database eliminates the implicit CAST function and jumps directly to the B-Tree leaf node in 0.8ms.",
      },
      {
        "id": "strat_cast_in_where",
        "title": "Explicit Cast on Column in WHERE",
        "sqlCommand": "SELECT customer_id, full_name, email FROM customers WHERE CAST(phone_number AS BIGINT) = 14155552671;",
        "isOptimal": False,
        "resultingCost": 285000,
        "resultingLatencyMs": 3400,
        "executionPlanSummary": "Seq Scan on customers -> Function applied to all 8,000,000 rows",
        "engineExplanation": "Trap! Applying CAST on the column phone_number still requires evaluating the function across every single row in the table, completely blinding the B-Tree index.",
      },
      {
        "id": "strat_add_composite_phone_email",
        "title": "Add Composite Index on (phone_number, email)",
        "sqlCommand": "CREATE INDEX idx_cust_phone_email ON customers(phone_number, email);",
        "isOptimal": False,
        "resultingCost": 215400,
        "resultingLatencyMs": 2850,
        "executionPlanSummary": "Seq Scan on customers (Still ignores index due to numeric type conversion)",
        "engineExplanation": "Useless index! Adding more columns to the index does not solve the type mismatch. The engine still cannot seek on a VARCHAR index when given an INT.",
      },
    ],
    "keyTakeaway": "Type precedence rules: When comparing string and numeric types, SQL engines convert strings to numbers. Wrapping the column in an implicit conversion prevents B-Tree seek traversal.",
  },
  {
    "id": "like_leading_wildcard_reverse",
    "title": "The Suffix Search Leading Wildcard Trap",
    "difficulty": "Junior",
    "category": "text_search",
    "categoryLabel": "Text Search & Pattern Matching",
    "tableName": "products",
    "rowCount": "5,000,000 rows",
    "tableSizeDisk": "1.4 GB on disk",
    "slowQuery": """SELECT product_id, sku, name, price
FROM products
WHERE sku LIKE '%-PRO-MAX'
LIMIT 20;""",
    "initialCost": 142000,
    "initialLatencyMs": 1850,
    "initialPlanSummary": "Seq Scan on products (cost=0.00..142000.00 rows=20) Filter: (sku ~~ '%-PRO-MAX'::text)",
    "businessContext": "Warehouse inventory app searches products by model suffix. Standard B-Tree index on sku exists but query takes nearly 2 seconds scanning every row.",
    "strategies": [
      {
        "id": "strat_reverse_expression_optimal",
        "title": "Reverse Expression Index with REVERSE()",
        "sqlCommand": """CREATE INDEX idx_products_sku_rev ON products (REVERSE(sku) text_pattern_ops);
-- Rewrite Query:
SELECT product_id, sku, name, price FROM products WHERE REVERSE(sku) LIKE REVERSE('%-PRO-MAX') LIMIT 20;""",
        "isOptimal": True,
        "resultingCost": 8.5,
        "resultingLatencyMs": 1.2,
        "executionPlanSummary": "Index Scan using idx_products_sku_rev -> Converts suffix match into prefix seek",
        "engineExplanation": "Genius! REVERSE('%-PRO-MAX') turns into 'XAM-ORP-%'. Because the wildcard is now at the END, the B-Tree can seek to the 'XAM-ORP' prefix directly in 1.2ms!",
      },
      {
        "id": "strat_standard_btree_sku",
        "title": "Standard B-Tree Index on sku",
        "sqlCommand": "CREATE INDEX idx_products_sku ON products(sku);",
        "isOptimal": False,
        "resultingCost": 142000,
        "resultingLatencyMs": 1840,
        "executionPlanSummary": "Seq Scan on products (Ignored B-Tree index due to leading wildcard)",
        "engineExplanation": "B-Tree keys are sorted left-to-right. A leading wildcard '%' means any character can start the string, forcing the engine to inspect every single record.",
      },
      {
        "id": "strat_ilike_scan",
        "title": "Use Case-Insensitive ILIKE",
        "sqlCommand": "SELECT product_id, sku, name FROM products WHERE sku ILIKE '%-PRO-MAX' LIMIT 20;",
        "isOptimal": False,
        "resultingCost": 180000,
        "resultingLatencyMs": 2400,
        "executionPlanSummary": "Seq Scan on products -> ILIKE is even slower due to lowercasing overhead",
        "engineExplanation": "Worse! ILIKE does not fix the leading wildcard and adds CPU overhead of lowercase byte comparisons per row.",
      },
    ],
    "keyTakeaway": "Standard B-Tree indexes cannot seek with a leading wildcard ('%suffix'). For suffix queries, index REVERSE(col) and query with REVERSE(pattern) to convert suffix into prefix seek.",
  },
  {
    "id": "function_on_indexed_column_date",
    "title": "Function Call on Date Column Blinds B-Tree",
    "difficulty": "Junior",
    "category": "expression_indexes",
    "categoryLabel": "Expression & Functional Indexes",
    "tableName": "user_registrations",
    "rowCount": "12,000,000 rows",
    "tableSizeDisk": "3.2 GB on disk",
    "slowQuery": """SELECT user_id, email, created_at
FROM user_registrations
WHERE DATE(created_at) = '2026-03-24';""",
    "initialCost": 310500,
    "initialLatencyMs": 3950,
    "initialPlanSummary": "Seq Scan on user_registrations (cost=0.00..310500.00) Filter: (date(created_at) = '2026-03-24'::date)",
    "businessContext": "Daily sign-up dashboard runs every morning to calculate yesterday's new registrations. Query scans 12 million rows despite having an index on created_at.",
    "strategies": [
      {
        "id": "strat_half_open_range_optimal",
        "title": "Rewrite to Half-Open Timestamp Range (>= start AND < next_day)",
        "sqlCommand": """SELECT user_id, email, created_at
FROM user_registrations
WHERE created_at >= '2026-03-24 00:00:00' 
  AND created_at < '2026-03-25 00:00:00';""",
        "isOptimal": True,
        "resultingCost": 14.2,
        "resultingLatencyMs": 1.5,
        "executionPlanSummary": "Index Scan using idx_registrations_created_at -> B-Tree Range Seek",
        "engineExplanation": "Champion! By rewriting DATE(created_at) into a range query [start, end), the existing B-Tree index on created_at is utilized directly without any schema change or DDL!",
      },
      {
        "id": "strat_functional_index_date",
        "title": "Create Functional Index on DATE(created_at)",
        "sqlCommand": "CREATE INDEX idx_reg_date ON user_registrations(DATE(created_at));",
        "isOptimal": False,
        "resultingCost": 85.0,
        "resultingLatencyMs": 12.0,
        "executionPlanSummary": "Bitmap Index Scan on idx_reg_date (Works, but adds redundant index overhead)",
        "engineExplanation": "Functional index works, but consumes 350 MB extra disk space and slows down every INSERT when a simple query rewrite uses the existing index for free.",
      },
      {
        "id": "strat_between_inclusive",
        "title": "Use BETWEEN with 23:59:59",
        "sqlCommand": "SELECT user_id, email FROM user_registrations WHERE created_at BETWEEN '2026-03-24 00:00:00' AND '2026-03-24 23:59:59';",
        "isOptimal": False,
        "resultingCost": 22.0,
        "resultingLatencyMs": 4.5,
        "executionPlanSummary": "Index Scan -> Accuracy Hazard: Misses sub-second microsecond rows",
        "engineExplanation": "Bug hazard! Timestamps with milliseconds (e.g. 23:59:59.850) will be skipped because they fall after 23:59:59.000. Always use half-open intervals >= and <.",
      },
    ],
    "keyTakeaway": "Never wrap indexed columns in functions like DATE(), YEAR(), or UPPER() in the WHERE clause. Always rewrite conditions into range boundaries on the raw column.",
  },
  {
    "id": "low_cardinality_boolean_index",
    "title": "The Low-Cardinality Flag Index Trap",
    "difficulty": "Junior",
    "category": "selectivity",
    "categoryLabel": "Index Selectivity & Cardinality",
    "tableName": "accounts",
    "rowCount": "20,000,000 rows",
    "tableSizeDisk": "5.8 GB on disk",
    "slowQuery": """SELECT account_id, balance, email
FROM accounts
WHERE is_active = true;""",
    "initialCost": 485000,
    "initialLatencyMs": 5200,
    "initialPlanSummary": "Seq Scan on accounts (cost=0.00..485000.00 rows=19600000) Filter: is_active",
    "businessContext": "Fintech platform runs an active user balance check. 98% of all accounts have is_active = true. A junior dev added CREATE INDEX idx_accounts_active ON accounts(is_active) but Postgres refuses to use it.",
    "strategies": [
      {
        "id": "strat_explain_low_cardinality_optimal",
        "title": "Accept Seq Scan for 98% match, or use Partial Index for the 2% Inactive",
        "sqlCommand": """-- For querying inactive accounts (the 2% minority):
CREATE INDEX idx_inactive_accounts ON accounts(account_id, balance) WHERE is_active = false;
-- For the 98% active query, sequential scan is mathematically faster than random I/O.""",
        "isOptimal": True,
        "resultingCost": 12.0,
        "resultingLatencyMs": 1.1,
        "executionPlanSummary": "Table scan is optimal for 98% selectivity; Partial index handles the rare 2% subset.",
        "engineExplanation": "Correct! When a query returns 98% of a table, reading through an index would require 19.6 million random page lookups. A sequential scan reads data blocks linearly at NVMe speed. Indexes only help high-selectivity (<5-10%) queries.",
      },
      {
        "id": "strat_force_index_scan",
        "title": "Force Index Scan with SET enable_seqscan = off",
        "sqlCommand": "SET enable_seqscan = off; SELECT account_id, balance FROM accounts WHERE is_active = true;",
        "isOptimal": False,
        "resultingCost": 1850000,
        "resultingLatencyMs": 28000,
        "executionPlanSummary": "Index Scan using idx_accounts_active (cost=0.56..1850000.00) -> 5x SLOWER!",
        "engineExplanation": "Catastrophic! Forcing an index scan for 98% of rows turns sequential block reading into millions of random disk seeks, ballooning query latency from 5s to 28s.",
      },
      {
        "id": "strat_cluster_table",
        "title": "CLUSTER accounts USING idx_accounts_active",
        "sqlCommand": "CLUSTER accounts USING idx_accounts_active;",
        "isOptimal": False,
        "resultingCost": 350000,
        "resultingLatencyMs": 4100,
        "executionPlanSummary": "Rewrites entire 5.8 GB table on disk with heavy exclusive lock",
        "engineExplanation": "Heavy lock outage: CLUSTER locks the table against all writes for minutes, and order degrades immediately as new records are inserted.",
      },
    ],
    "keyTakeaway": "Indexes are designed for high selectivity. If a query matches >20% of a table (like a boolean true on 98% active users), sequential scanning is faster than index page hops.",
  },
  {
    "id": "composite_index_leftmost_skip",
    "title": "Skipping the Leftmost Prefix in Composite Indexes",
    "difficulty": "Junior",
    "category": "composite_indexing",
    "categoryLabel": "Composite Indexing",
    "tableName": "inventory",
    "rowCount": "10,000,000 rows",
    "tableSizeDisk": "2.8 GB on disk",
    "slowQuery": """SELECT item_id, warehouse_id, quantity
FROM inventory
WHERE warehouse_id = 42 AND quantity < 10;""",
    "initialCost": 265000,
    "initialLatencyMs": 3100,
    "initialPlanSummary": "Seq Scan on inventory (cost=0.00..265000.00) Filter: ((warehouse_id = 42) AND (quantity < 10))",
    "businessContext": "Warehouse replenishment alert checks low stock in warehouse 42. Table has a composite index on (sku, warehouse_id, quantity), yet the query scans the whole table.",
    "strategies": [
      {
        "id": "strat_composite_wh_qty_optimal",
        "title": "Create Index on Filtered Columns: (warehouse_id, quantity)",
        "sqlCommand": "CREATE INDEX idx_inv_wh_qty ON inventory(warehouse_id, quantity) INCLUDE (item_id);",
        "isOptimal": True,
        "resultingCost": 9.4,
        "resultingLatencyMs": 1.1,
        "executionPlanSummary": "Index Only Scan using idx_inv_wh_qty -> Zero Heap Reads",
        "engineExplanation": "Winner! Adheres to Leftmost Prefix: equality on warehouse_id first, followed by range on quantity. INCLUDE eliminates heap table lookups.",
      },
      {
        "id": "strat_single_index_qty",
        "title": "Single Column Index on quantity",
        "sqlCommand": "CREATE INDEX idx_inv_qty ON inventory(quantity);",
        "isOptimal": False,
        "resultingCost": 78000,
        "resultingLatencyMs": 950,
        "executionPlanSummary": "Bitmap Index Scan on quantity -> Filter on warehouse_id applied to thousands of rows",
        "engineExplanation": "Sub-optimal. An index on quantity finds all low-stock items across all warehouses worldwide, forcing the engine to filter warehouse_id row-by-row.",
      },
      {
        "id": "strat_index_hint_force",
        "title": "Rely on Existing (sku, warehouse_id, quantity) Index",
        "sqlCommand": "/* Query unchanged, hoping database skips sku */",
        "isOptimal": False,
        "resultingCost": 265000,
        "resultingLatencyMs": 3100,
        "executionPlanSummary": "Seq Scan -> Cannot seek B-Tree without leading 'sku' column",
        "engineExplanation": "A composite index B-Tree is ordered by sku first. Without a sku predicate, the index cannot be searched from root to leaf.",
      },
    ],
    "keyTakeaway": "Leftmost Prefix Rule: A composite index on (A, B, C) can satisfy queries on (A) or (A, B), but CANNOT be used efficiently for queries filtering only on (B) or (B, C).",
  },
  {
    "id": "unindexed_foreign_key_cascade",
    "title": "Unindexed Foreign Key Causes Cascade Lock Meltdown",
    "difficulty": "Junior",
    "category": "foreign_keys",
    "categoryLabel": "Foreign Keys & Locking",
    "tableName": "order_items",
    "rowCount": "40,000,000 rows",
    "tableSizeDisk": "9.6 GB on disk",
    "slowQuery": """-- Transaction executing on parent table:
DELETE FROM orders WHERE order_id = 98124;""",
    "initialCost": 980000,
    "initialLatencyMs": 11500,
    "initialPlanSummary": "Seq Scan on order_items (cost=0.00..980000.00) Filter: (order_id = 98124) -> Table lock on child table!",
    "businessContext": "Deleting a canceled order in the admin portal freezes database operations for 12 seconds. Every other transaction trying to write to order_items gets blocked.",
    "strategies": [
      {
        "id": "strat_index_foreign_key_optimal",
        "title": "Create Index on Child Foreign Key: order_items(order_id)",
        "sqlCommand": "CREATE INDEX idx_order_items_order_id ON order_items(order_id);",
        "isOptimal": True,
        "resultingCost": 4.1,
        "resultingLatencyMs": 0.9,
        "executionPlanSummary": "Index Scan on order_items using idx_order_items_order_id -> Instant cascade check",
        "engineExplanation": "Essential! Relational databases do NOT automatically index foreign key columns on child tables. Without an index, parent DELETE/UPDATE forces a full sequential scan of 40M child rows with heavy locks.",
      },
      {
        "id": "strat_remove_foreign_key",
        "title": "Drop Foreign Key Constraint Completely",
        "sqlCommand": "ALTER TABLE order_items DROP CONSTRAINT fk_order_items_order;",
        "isOptimal": False,
        "resultingCost": 0.0,
        "resultingLatencyMs": 0.5,
        "executionPlanSummary": "Deletes immediately, but corrupts data integrity with orphaned rows",
        "engineExplanation": "Dangerous anti-pattern! Dropping referential integrity allows orphaned line items when bugs occur, breaking accounting audits.",
      },
      {
        "id": "strat_soft_delete_only",
        "title": "Switch to Soft Deletes without FK Index",
        "sqlCommand": "UPDATE orders SET is_deleted = true WHERE order_id = 98124;",
        "isOptimal": False,
        "resultingCost": 8.0,
        "resultingLatencyMs": 2.0,
        "executionPlanSummary": "Evades foreign key cascade on delete, but fails to fix cascade updates or referential checks",
        "engineExplanation": "Band-aid: While it avoids DELETE, any future cascade check or batch purge will still hit a 40M full table scan.",
      },
    ],
    "keyTakeaway": "Always index foreign key columns on child tables. Databases automatically index PRIMARY KEYs, but NEVER automatically index FOREIGN KEYs.",
  },
  {
    "id": "count_star_vs_count_column",
    "title": "Slow Full Table Row Counting",
    "difficulty": "Junior",
    "category": "aggregations",
    "categoryLabel": "Aggregations & Group By",
    "tableName": "page_views",
    "rowCount": "50,000,000 rows",
    "tableSizeDisk": "14.2 GB on disk",
    "slowQuery": """SELECT COUNT(session_id)
FROM page_views
WHERE site_id = 101;""",
    "initialCost": 1250000,
    "initialLatencyMs": 14200,
    "initialPlanSummary": "Seq Scan on page_views (cost=0.00..1250000.00) Filter: (site_id = 101)",
    "businessContext": "Tenant analytics page counts visits for site 101. Loading the dashboard takes 14 seconds scanning 50M rows off disk.",
    "strategies": [
      {
        "id": "strat_covering_count_optimal",
        "title": "Covering Index for Index-Only Count: (site_id, session_id)",
        "sqlCommand": "CREATE INDEX idx_pv_site_sess ON page_views(site_id, session_id);",
        "isOptimal": True,
        "resultingCost": 18.5,
        "resultingLatencyMs": 3.2,
        "executionPlanSummary": "Index Only Scan using idx_pv_site_sess -> Zero table block fetches",
        "engineExplanation": "Winner! By covering both the filter (site_id) and the counted column (session_id), the engine counts index pointers directly without fetching 14 GB of table heap data.",
      },
      {
        "id": "strat_single_index_site",
        "title": "Index on site_id only",
        "sqlCommand": "CREATE INDEX idx_pv_site ON page_views(site_id);",
        "isOptimal": False,
        "resultingCost": 185000,
        "resultingLatencyMs": 2400,
        "executionPlanSummary": "Bitmap Heap Scan -> Must fetch table rows to check if session_id IS NOT NULL",
        "engineExplanation": "COUNT(col) ignores NULLs. Because the index only has site_id, the engine must still visit table heap pages to check if session_id is NULL.",
      },
      {
        "id": "strat_increase_workmem",
        "title": "Increase work_mem to 1GB",
        "sqlCommand": "SET work_mem = '1GB'; SELECT COUNT(session_id) FROM page_views WHERE site_id = 101;",
        "isOptimal": False,
        "resultingCost": 1250000,
        "resultingLatencyMs": 13900,
        "executionPlanSummary": "Seq Scan -> work_mem has no effect on counting rows without sorting",
        "engineExplanation": "work_mem is used for sorting and hash tables, not for accelerating row counting on table scans.",
      },
    ],
    "keyTakeaway": "COUNT(column) requires verifying that the column is NOT NULL. A composite index covering the filter and the target column turns a table scan into a fast index-only count.",
  },
  {
    "id": "select_star_heap_fetch",
    "title": "SELECT * Destroys Index-Only Scan",
    "difficulty": "Junior",
    "category": "covering_indexes",
    "categoryLabel": "Covering Indexes & Index-Only Scans",
    "tableName": "members",
    "rowCount": "8,000,000 rows",
    "tableSizeDisk": "2.4 GB on disk",
    "slowQuery": """SELECT *
FROM members
WHERE status = 'VERIFIED' AND country = 'US'
ORDER BY joined_date DESC
LIMIT 50;""",
    "initialCost": 182000,
    "initialLatencyMs": 2150,
    "initialPlanSummary": "Seq Scan on members -> 45 columns fetched from heap with disk filesort",
    "businessContext": "Member directory API returns 50 latest verified users. Table has 45 wide columns (biography, profile_json, address). Query fetches everything with SELECT *.",
    "strategies": [
      {
        "id": "strat_select_columns_include_optimal",
        "title": "Select Specific Columns with Covering INCLUDE Index",
        "sqlCommand": """CREATE INDEX idx_members_status_country_date ON members(status, country, joined_date DESC)
INCLUDE (member_id, username, email);

-- Query:
SELECT member_id, username, email, joined_date
FROM members
WHERE status = 'VERIFIED' AND country = 'US'
ORDER BY joined_date DESC
LIMIT 50;""",
        "isOptimal": True,
        "resultingCost": 8.1,
        "resultingLatencyMs": 0.9,
        "executionPlanSummary": "Index Only Scan using idx_members_status_country_date -> Zero Heap Page Reads",
        "engineExplanation": "Champion! By requesting only the 4 needed columns instead of 45 wide columns, the query is resolved 100% within B-Tree leaf pages without touching the heap table.",
      },
      {
        "id": "strat_index_all_columns",
        "title": "Create Index on All 45 Columns",
        "sqlCommand": "CREATE INDEX idx_members_all ON members(status, country, joined_date, username, email, bio, ...);",
        "isOptimal": False,
        "resultingCost": 350000,
        "resultingLatencyMs": 4200,
        "executionPlanSummary": "Exceeds B-Tree maximum index tuple size (2704 bytes limit)",
        "engineExplanation": "Error: B-Tree indexes have strict row size limits (usually 1/3 of a page, ~2704 bytes in Postgres). Indexing wide text columns fails or creates catastrophic write bloat.",
      },
      {
        "id": "strat_filter_only_index",
        "title": "Index only (status, country)",
        "sqlCommand": "CREATE INDEX idx_mem_st_co ON members(status, country);",
        "isOptimal": False,
        "resultingCost": 42000,
        "resultingLatencyMs": 480,
        "executionPlanSummary": "Bitmap Heap Scan -> Still requires separate disk filesort for joined_date DESC",
        "engineExplanation": "Without joined_date in the index, the database must retrieve all matching rows and sort them in memory or disk.",
      },
    ],
    "keyTakeaway": "SELECT * forces the engine to visit the heap table for every row, disabling Index-Only Scans. Explicit column selection combined with INCLUDE enables sub-millisecond execution.",
  },
  {
    "id": "orderby_asc_desc_composite",
    "title": "Mixed Direction Sort Filesort Penalty",
    "difficulty": "Junior",
    "category": "sorting",
    "categoryLabel": "Multi-Column Sorting",
    "tableName": "leaderboard",
    "rowCount": "6,000,000 rows",
    "tableSizeDisk": "1.8 GB on disk",
    "slowQuery": """SELECT user_id, score, submission_time
FROM leaderboard
ORDER BY score DESC, submission_time ASC
LIMIT 25;""",
    "initialCost": 154000,
    "initialLatencyMs": 1920,
    "initialPlanSummary": "Seq Scan on leaderboard -> Sort: External Merge Disk (score DESC, submission_time ASC)",
    "businessContext": "Gaming platform leaderboard displays highest score first, with ties broken by earliest submission time. Sorting 6 million rows causes CPU spikes on every page load.",
    "strategies": [
      {
        "id": "strat_matching_direction_index_optimal",
        "title": "Composite Index with Matching Direction: (score DESC, submission_time ASC)",
        "sqlCommand": "CREATE INDEX idx_leaderboard_score_time ON leaderboard(score DESC, submission_time ASC);",
        "isOptimal": True,
        "resultingCost": 5.2,
        "resultingLatencyMs": 0.8,
        "executionPlanSummary": "Index Scan using idx_leaderboard_score_time -> Zero Sorting Overhead",
        "engineExplanation": "Winner! Standard B-Trees can only be scanned forward (ASC, ASC) or backward (DESC, DESC). When sorting directions are mixed (DESC, ASC), the index definition MUST explicitly declare matching column directions.",
      },
      {
        "id": "strat_default_asc_index",
        "title": "Default Composite Index: (score, submission_time)",
        "sqlCommand": "CREATE INDEX idx_lb_default ON leaderboard(score, submission_time);",
        "isOptimal": False,
        "resultingCost": 128000,
        "resultingLatencyMs": 1550,
        "executionPlanSummary": "Index Scan -> Sort: External Disk Merge (Cannot traverse mixed directions)",
        "engineExplanation": "Trap! Default indexes are (ASC, ASC). Scanning backward gives (DESC, DESC). The engine cannot walk backward on score while walking forward on submission_time.",
      },
      {
        "id": "strat_increase_sort_buffer",
        "title": "Increase sort_buffer_size to 64MB",
        "sqlCommand": "SET sort_buffer_size = 67108864; SELECT ... FROM leaderboard ...",
        "isOptimal": False,
        "resultingCost": 98000,
        "resultingLatencyMs": 1100,
        "executionPlanSummary": "In-Memory Quicksort instead of disk spill, but still sorts 6M rows",
        "engineExplanation": "Band-aid: Memory quicksort is faster than disk merge, but wasting CPU cycles sorting 6M rows on every page refresh exhausts server capacity.",
      },
    ],
    "keyTakeaway": "B-Tree indexes can scan forward (A ASC, B ASC) or reverse (A DESC, B DESC). Queries with mixed directions (A DESC, B ASC) require an index declared with those exact sort directions.",
  },
  {
    "id": "redundant_index_overhead",
    "title": "Redundant Indexes Cripple Write Throughput",
    "difficulty": "Junior",
    "category": "index_maintenance",
    "categoryLabel": "Index Maintenance & Bloat",
    "tableName": "payments",
    "rowCount": "15,000,000 rows",
    "tableSizeDisk": "5.2 GB on disk",
    "slowQuery": """-- High-frequency payment insertion:
INSERT INTO payments (payment_id, user_id, amount, status, created_at)
VALUES (994821, 1042, 150.00, 'COMPLETED', NOW());""",
    "initialCost": 85.0,
    "initialLatencyMs": 84,
    "initialPlanSummary": "Insert into payments -> Updating 8 secondary B-Tree indexes! (High I/O write amplification)",
    "businessContext": "Payment processing throughput degraded to 15 writes/sec. DBA audit discovered 8 overlapping indexes: (user_id), (user_id, status), (user_id, status, created_at), (status), etc.",
    "strategies": [
      {
        "id": "strat_consolidate_indexes_optimal",
        "title": "Drop Redundant Prefix Indexes, Keep Master Composite",
        "sqlCommand": """-- Drop redundant prefix indexes:
DROP INDEX idx_payments_user_id;
DROP INDEX idx_payments_user_status;
-- Retain the covering composite:
-- idx_payments_user_status_created (user_id, status, created_at) covers all three!""",
        "isOptimal": True,
        "resultingCost": 8.0,
        "resultingLatencyMs": 2.1,
        "executionPlanSummary": "Insert write latency drops from 84ms to 2.1ms (75% less index updates)",
        "engineExplanation": "Champion! Because (user_id, status, created_at) already has (user_id) and (user_id, status) as leftmost prefixes, maintaining the separate single-column indexes was 100% redundant write overhead.",
      },
      {
        "id": "strat_delay_index_maintenance",
        "title": "Drop Indexes Before Batch and Recreate",
        "sqlCommand": "DROP ALL INDEXES; INSERT ...; RECREATE INDEXES;",
        "isOptimal": False,
        "resultingCost": 0.0,
        "resultingLatencyMs": 0.0,
        "executionPlanSummary": "Invalid for OLTP live customer payments! Locks production tables.",
        "engineExplanation": "Dangerous: Dropping indexes works for bulk data warehouse loading, but in live 24/7 payment processing, read queries would immediately time out with table scans.",
      },
      {
        "id": "strat_increase_wal_buffers",
        "title": "Increase wal_buffers to 64MB",
        "sqlCommand": "ALTER SYSTEM SET wal_buffers = '64MB';",
        "isOptimal": False,
        "resultingCost": 80.0,
        "resultingLatencyMs": 78,
        "executionPlanSummary": "Minor I/O smoothing, but does not solve 8 B-Tree leaf page splits per insert",
        "engineExplanation": "Increasing WAL buffers helps buffer spikes, but does not eliminate the physical CPU and disk cost of updating 8 separate index trees on every insert.",
      },
    ],
    "keyTakeaway": "An index on (A, B, C) already provides an index on (A) and (A, B). Storing redundant sub-prefix indexes wastes gigabytes of RAM and throttles INSERT/UPDATE speeds.",
  },
  {
    "id": "is_null_partial_index",
    "title": "Sparse NULL Lookup in 10M Row Table",
    "difficulty": "Junior",
    "category": "partial_indexes",
    "categoryLabel": "Partial & Filtered Indexes",
    "tableName": "shipments",
    "rowCount": "10,000,000 rows",
    "tableSizeDisk": "3.4 GB on disk",
    "slowQuery": """SELECT shipment_id, tracking_number, destination
FROM shipments
WHERE delivered_at IS NULL;""",
    "initialCost": 245000,
    "initialLatencyMs": 2900,
    "initialPlanSummary": "Seq Scan on shipments (cost=0.00..245000.00 rows=50000) Filter: (delivered_at IS NULL)",
    "businessContext": "Delivery dispatcher monitors active in-flight packages. 99.5% of packages are delivered (delivered_at is NOT NULL). Only 50,000 packages (0.5%) are in transit.",
    "strategies": [
      {
        "id": "strat_partial_is_null_optimal",
        "title": "Create Partial Index for In-Flight Shipments: WHERE delivered_at IS NULL",
        "sqlCommand": "CREATE INDEX idx_shipments_in_flight ON shipments(shipment_id, tracking_number, destination) WHERE delivered_at IS NULL;",
        "isOptimal": True,
        "resultingCost": 12.5,
        "resultingLatencyMs": 1.2,
        "executionPlanSummary": "Index Only Scan using idx_shipments_in_flight -> 4 MB tiny index",
        "engineExplanation": "Masterclass! Instead of indexing all 10 million rows (300 MB), the partial index stores ONLY the 50,000 in-flight records. The index fits entirely in 4 MB of L3 CPU cache!",
      },
      {
        "id": "strat_btree_full_delivered",
        "title": "Full B-Tree Index on delivered_at",
        "sqlCommand": "CREATE INDEX idx_shipments_delivered_at ON shipments(delivered_at);",
        "isOptimal": False,
        "resultingCost": 4800,
        "resultingLatencyMs": 65,
        "executionPlanSummary": "Bitmap Heap Scan on shipments (Indexes 9.95M delivered rows needlessly)",
        "engineExplanation": "Wasteful: A full B-tree indexes 9,950,000 rows that are never queried by this endpoint, consuming 300MB of RAM and slowing down every delivery confirmation update.",
      },
      {
        "id": "strat_not_null_default",
        "title": "Set Default Timestamp to '1970-01-01' instead of NULL",
        "sqlCommand": "UPDATE shipments SET delivered_at = '1970-01-01' WHERE delivered_at IS NULL;",
        "isOptimal": False,
        "resultingCost": 245000,
        "resultingLatencyMs": 2900,
        "executionPlanSummary": "Still full table scan without index, and corrupts domain semantics",
        "engineExplanation": "Anti-pattern: Magic sentinel dates break business logic and do not improve query performance without an index.",
      },
    ],
    "keyTakeaway": "When searching for rare NULL values (e.g. unfinished tasks, in-transit items), create a Partial Index with WHERE col IS NULL. It creates a featherweight index that updates at lightning speed.",
  },
  {
    "id": "math_expression_in_where",
    "title": "Arithmetic Operations on Columns in WHERE Clause",
    "difficulty": "Junior",
    "category": "expression_indexes",
    "categoryLabel": "Expression & Functional Indexes",
    "tableName": "invoices",
    "rowCount": "7,000,000 rows",
    "tableSizeDisk": "2.1 GB on disk",
    "slowQuery": """SELECT invoice_id, customer_id, amount
FROM invoices
WHERE amount * 1.10 > 500.00;""",
    "initialCost": 185000,
    "initialLatencyMs": 2200,
    "initialPlanSummary": "Seq Scan on invoices (cost=0.00..185000.00) Filter: ((amount * 1.10) > 500.00)",
    "businessContext": "Billing service queries high-value transactions including sales tax. Table has an index on amount, but the query multiplies by 1.10 on the left-hand side.",
    "strategies": [
      {
        "id": "strat_algebraic_isolation_optimal",
        "title": "Isolate the Column Algebraically: amount > (500.00 / 1.10)",
        "sqlCommand": """SELECT invoice_id, customer_id, amount
FROM invoices
WHERE amount > (500.00 / 1.10);""",
        "isOptimal": True,
        "resultingCost": 9.2,
        "resultingLatencyMs": 1.1,
        "executionPlanSummary": "Index Scan using idx_invoices_amount -> Pure B-Tree Range Seek",
        "engineExplanation": "Winner! By dividing 500.00 by 1.10 on the right side, the math is evaluated ONCE as a constant (454.54). The unadorned column 'amount' can now perform an instant B-Tree index seek.",
      },
      {
        "id": "strat_expression_index_tax",
        "title": "Create Expression Index: ((amount * 1.10))",
        "sqlCommand": "CREATE INDEX idx_inv_amount_tax ON invoices((amount * 1.10));",
        "isOptimal": False,
        "resultingCost": 12.0,
        "resultingLatencyMs": 1.6,
        "executionPlanSummary": "Index Scan on idx_inv_amount_tax (Adds unnecessary DDL & index maintenance)",
        "engineExplanation": "Overkill: Adding a dedicated expression index consumes 180MB of disk and slows down invoice creation when a 5-second SQL rewrite achieves the exact same 1ms speed.",
      },
      {
        "id": "strat_cast_float",
        "title": "Cast to FLOAT",
        "sqlCommand": "SELECT invoice_id, customer_id, amount FROM invoices WHERE (amount::float * 1.10) > 500.00;",
        "isOptimal": False,
        "resultingCost": 195000,
        "resultingLatencyMs": 2350,
        "executionPlanSummary": "Seq Scan -> Still evaluates arithmetic per row",
        "engineExplanation": "Casting does not isolate the column from the multiplication operator.",
      },
    ],
    "keyTakeaway": "Always keep indexed columns 'naked' in WHERE clauses. Move arithmetic operations, constants, and functions to the right-hand side so the query planner evaluates them once as a constant.",
  },
  {
    "id": "in_clause_vs_equality_chain",
    "title": "Massive IN (...) Clause with 5,000 Elements",
    "difficulty": "Junior",
    "category": "query_rewrites",
    "categoryLabel": "Query Rewrites & Predicates",
    "tableName": "products",
    "rowCount": "12,000,000 rows",
    "tableSizeDisk": "3.5 GB on disk",
    "slowQuery": """SELECT product_id, title, price
FROM products
WHERE category_id IN (1, 2, 3, ... 5000 ids passed from API);""",
    "initialCost": 420000,
    "initialLatencyMs": 6800,
    "initialPlanSummary": "Bitmap Heap Scan with 5000 Index Scans -> Optimizer parses 2MB SQL text string",
    "businessContext": "E-commerce search passes 5,000 category IDs into an IN clause generated by application code. Database parser chokes and planner execution spikes CPU to 100%.",
    "strategies": [
      {
        "id": "strat_inner_join_temp_optimal",
        "title": "Rewrite to JOIN with VALUES or Temporary Array: = ANY(ARRAY[...])",
        "sqlCommand": """SELECT p.product_id, p.title, p.price
FROM products p
JOIN unnest($1::int[]) AS c(category_id) ON p.category_id = c.category_id;
-- Or in Postgres: WHERE category_id = ANY($1::int[])""",
        "isOptimal": True,
        "resultingCost": 35.0,
        "resultingLatencyMs": 4.2,
        "executionPlanSummary": "Hash Join with unnest(ARRAY) -> Fast single parameterized query",
        "engineExplanation": "Champion! Passing an array parameter with ANY() or UNNEST() allows the optimizer to perform an efficient Hash Join or batch index lookup without bloating SQL parse trees with 5,000 AST nodes.",
      },
      {
        "id": "strat_split_individual_queries",
        "title": "Loop and Execute 5,000 Individual Single Queries",
        "sqlCommand": "for id in ids: SELECT ... WHERE category_id = id",
        "isOptimal": False,
        "resultingCost": 15000,
        "resultingLatencyMs": 9500,
        "executionPlanSummary": "5,000 Network Roundtrips (N+1 query disaster)",
        "engineExplanation": "Terrible! 5,000 individual queries incur 5,000 network round-trips, turning a 6-second query into a 10-second latency nightmare.",
      },
      {
        "id": "strat_or_chain",
        "title": "Convert IN to OR chain: category_id = 1 OR category_id = 2...",
        "sqlCommand": "SELECT ... WHERE category_id = 1 OR category_id = 2 ...",
        "isOptimal": False,
        "resultingCost": 450000,
        "resultingLatencyMs": 7200,
        "executionPlanSummary": "OR chain is syntactically equivalent to IN, but slower to parse",
        "engineExplanation": "OR chains have higher parsing complexity and force the optimizer to perform identical Bitmap OR scans.",
      },
    ],
    "keyTakeaway": "Avoid generating massive IN clauses with thousands of literals. Pass arrays with ANY(ARRAY[...]) or JOIN against UNNEST() to keep execution plans lean and parameterized.",
  },
  {
    "id": "uuid_v4_vs_uuid_v7_fragmentation",
    "title": "Random UUID v4 B-Tree Page Split Thrashing",
    "difficulty": "Junior",
    "category": "primary_keys",
    "categoryLabel": "Primary Key Design & Storage",
    "tableName": "event_log",
    "rowCount": "25,000,000 rows",
    "tableSizeDisk": "8.4 GB on disk",
    "slowQuery": """-- High throughput event ingestion:
INSERT INTO event_log (id, event_type, payload, created_at)
VALUES (gen_random_uuid(), 'CLICK', '{"button": "buy"}', NOW());""",
    "initialCost": 95.0,
    "initialLatencyMs": 68,
    "initialPlanSummary": "Insert into event_log -> Random B-Tree Page Splits on Primary Key",
    "businessContext": "High-scale analytics ingestion: As table crossed 20 million rows, INSERT latency spiked from 1ms to 68ms. Buffer pool hit ratio plummeted from 99% to 64%.",
    "strategies": [
      {
        "id": "strat_uuid_v7_monotonic_optimal",
        "title": "Switch to Time-Sorted Monotonic UUID v7 or BIGSERIAL",
        "sqlCommand": """-- Use UUID v7 (Time-prefixed UUID) or BIGINT IDENTITY:
ALTER TABLE event_log ALTER COLUMN id SET DEFAULT uuid_generate_v7();
-- Inserts append strictly to rightmost B-Tree leaf pages!""",
        "isOptimal": True,
        "resultingCost": 4.0,
        "resultingLatencyMs": 0.9,
        "executionPlanSummary": "Append-only leaf page inserts -> 0% random page splits, 99.8% Buffer Pool Hit",
        "engineExplanation": "Winner! Random UUID v4 scatters inserts uniformly across all 500,000 index leaf pages. Because all pages cannot fit in RAM, every insert triggers random disk reads and leaf page splits. UUID v7 is monotonically increasing, appending sequentially to the rightmost leaf.",
      },
      {
        "id": "strat_increase_buffer_pool",
        "title": "Double shared_buffers / innodb_buffer_pool_size",
        "sqlCommand": "SET shared_buffers = '32GB';",
        "isOptimal": False,
        "resultingCost": 60.0,
        "resultingLatencyMs": 42,
        "executionPlanSummary": "Temporarily delays page thrashing, but fails as data continues growing",
        "engineExplanation": "Expensive hardware band-aid: As soon as table size exceeds the new RAM allocation, random I/O thrashing immediately returns.",
      },
      {
        "id": "strat_hash_index_pk",
        "title": "Replace B-Tree with Hash Index on Primary Key",
        "sqlCommand": "CREATE INDEX idx_event_hash ON event_log USING HASH(id);",
        "isOptimal": False,
        "resultingCost": 50.0,
        "resultingLatencyMs": 35,
        "executionPlanSummary": "Hash indexes cannot enforce PRIMARY KEY constraints or support range scans",
        "engineExplanation": "Invalid in most engines: Primary keys require B-Tree indexes. Furthermore, hash indexes still suffer random distribution without clustering benefits.",
      },
    ],
    "keyTakeaway": "Random UUID v4 values destroy B-Tree cache locality by forcing random page splits across the entire index tree. Always use time-ordered identifiers (UUID v7, TSID, or BIGINT) for primary keys.",
  },
  {
    "id": "char_vs_varchar_padding",
    "title": "Blank-Padded CHAR(255) Space Bloat",
    "difficulty": "Junior",
    "category": "data_types",
    "categoryLabel": "Data Types & Storage",
    "tableName": "countries",
    "rowCount": "2,000,000 rows",
    "tableSizeDisk": "1.2 GB on disk",
    "slowQuery": """SELECT country_code, country_name
FROM countries
WHERE country_code = 'US';""",
    "initialCost": 38000,
    "initialLatencyMs": 420,
    "initialPlanSummary": "Seq Scan on countries -> Table size is 1.2 GB despite having only 2M small rows",
    "businessContext": "Schema design flaw: country_code was declared as CHAR(255) instead of CHAR(2) or VARCHAR(2). The database blank-pads every row with 253 trailing spaces.",
    "strategies": [
      {
        "id": "strat_alter_column_varchar_optimal",
        "title": "Alter Column to CHAR(2) and Add Index",
        "sqlCommand": """ALTER TABLE countries ALTER COLUMN country_code TYPE VARCHAR(2);
CREATE INDEX idx_countries_code ON countries(country_code);""",
        "isOptimal": True,
        "resultingCost": 3.5,
        "resultingLatencyMs": 0.6,
        "executionPlanSummary": "Index Scan using idx_countries_code -> Table shrinks from 1.2 GB to 48 MB",
        "engineExplanation": "Champion! CHAR(255) reserves 255 bytes per row regardless of string length. Changing to VARCHAR(2) shrinks table disk size by 96%, fitting the entire table into CPU cache in 0.6ms.",
      },
      {
        "id": "strat_trim_in_where",
        "title": "Use TRIM(country_code) = 'US'",
        "sqlCommand": "SELECT * FROM countries WHERE TRIM(country_code) = 'US';",
        "isOptimal": False,
        "resultingCost": 45000,
        "resultingLatencyMs": 580,
        "executionPlanSummary": "Seq Scan with TRIM function overhead per row",
        "engineExplanation": "Makes it worse! Wrapping the column in TRIM() prevents index usage and burns CPU stripping whitespace.",
      },
      {
        "id": "strat_compress_table",
        "title": "Enable TOAST / ROW_FORMAT=COMPRESSED",
        "sqlCommand": "ALTER TABLE countries ROW_FORMAT=COMPRESSED;",
        "isOptimal": False,
        "resultingCost": 15000,
        "resultingLatencyMs": 180,
        "executionPlanSummary": "Table compression adds CPU decompression penalty on every read",
        "engineExplanation": "Fixing the wrong layer: Compressing bad schema types introduces CPU compression overhead instead of fixing the 253-byte space waste.",
      },
    ],
    "keyTakeaway": "Fixed-width CHAR(N) pads strings with whitespace up to length N. Use CHAR only for strictly fixed-length codes (e.g. CHAR(2) for ISO country codes); use VARCHAR for variable text.",
  },
  {
    "id": "limit_offset_shallow_vs_deep",
    "title": "Shallow vs Deep Pagination Pitfall",
    "difficulty": "Junior",
    "category": "pagination",
    "categoryLabel": "Pagination & Offset",
    "tableName": "blog_posts",
    "rowCount": "500,000 rows",
    "tableSizeDisk": "180 MB on disk",
    "slowQuery": """SELECT post_id, title, published_at
FROM blog_posts
ORDER BY published_at DESC
LIMIT 10 OFFSET 0;""",
    "initialCost": 18500,
    "initialLatencyMs": 145,
    "initialPlanSummary": "Seq Scan on blog_posts -> Sort: published_at DESC -> Limit 10",
    "businessContext": "Blog homepage displays the 10 most recent articles. Even with OFFSET 0, loading the homepage takes 145ms because the engine performs a full table scan and filesort.",
    "strategies": [
      {
        "id": "strat_index_published_at_optimal",
        "title": "Create Index on (published_at DESC) with Covering Columns",
        "sqlCommand": "CREATE INDEX idx_blog_published ON blog_posts(published_at DESC) INCLUDE (title, post_id);",
        "isOptimal": True,
        "resultingCost": 3.1,
        "resultingLatencyMs": 0.5,
        "executionPlanSummary": "Index Only Scan using idx_blog_published -> Fetches top 10 index leaf entries in 0.5ms",
        "engineExplanation": "Winner! An index on published_at DESC stores rows pre-sorted. The engine reads exactly 10 index leaf records from the top and stops immediately with zero sorting.",
      },
      {
        "id": "strat_keyset_for_offset_0",
        "title": "Rewrite to Keyset Pagination for Page 1",
        "sqlCommand": "SELECT post_id, title FROM blog_posts WHERE post_id > 0 LIMIT 10;",
        "isOptimal": False,
        "resultingCost": 14000,
        "resultingLatencyMs": 110,
        "executionPlanSummary": "Returns arbitrary 10 IDs without sorting by publication date",
        "engineExplanation": "Breaks business logic: Keyset pagination on post_id does not return the latest published articles.",
      },
      {
        "id": "strat_subquery_limit",
        "title": "Wrap in Subquery with LIMIT",
        "sqlCommand": "SELECT * FROM (SELECT * FROM blog_posts) b ORDER BY b.published_at DESC LIMIT 10;",
        "isOptimal": False,
        "resultingCost": 22000,
        "resultingLatencyMs": 180,
        "executionPlanSummary": "Subquery scan still requires full table scan and filesort",
        "engineExplanation": "Syntactic illusion: Wrapping a full table scan in a subquery does not create an index.",
      },
    ],
    "keyTakeaway": "Even for OFFSET 0, an ORDER BY clause without an index forces the database to sort the entire table in memory or disk. A matching B-Tree index satisfies ORDER BY ... LIMIT in sub-millisecond time.",
  },
  {
    "id": "text_prefix_index_length",
    "title": "Unbounded Text Index Exceeds Maximum Index Length",
    "difficulty": "Junior",
    "category": "prefix_indexes",
    "categoryLabel": "Index Size & Prefix Compression",
    "tableName": "web_bookmarks",
    "rowCount": "4,000,000 rows",
    "tableSizeDisk": "1.8 GB on disk",
    "slowQuery": """SELECT bookmark_id, url, user_id
FROM web_bookmarks
WHERE url = 'https://engineering.google.com/deepmind/article/transformer-scaling-laws';""",
    "initialCost": 92000,
    "initialLatencyMs": 1150,
    "initialPlanSummary": "Seq Scan on web_bookmarks Filter: (url = '...')",
    "businessContext": "Bookmarking tool looks up saved URLs. Trying to run CREATE INDEX on url (VARCHAR(2048)) throws Error 1071: Specified key was too long; max key length is 3072 bytes (or bloats index to 1.5 GB).",
    "strategies": [
      {
        "id": "strat_url_hash_generated_column_optimal",
        "title": "Generated SHA256 Column with Unique Index",
        "sqlCommand": """-- Add deterministic hash column:
ALTER TABLE web_bookmarks ADD COLUMN url_hash BYTEA 
GENERATED ALWAYS AS (digest(url, 'sha256')) STORED;

CREATE INDEX idx_bookmarks_url_hash ON web_bookmarks(url_hash);

-- Query:
SELECT bookmark_id, url, user_id FROM web_bookmarks 
WHERE url_hash = digest('https://engineering.google.com/...', 'sha256') 
  AND url = 'https://engineering.google.com/...';""",
        "isOptimal": True,
        "resultingCost": 4.1,
        "resultingLatencyMs": 0.8,
        "executionPlanSummary": "Index Scan using idx_bookmarks_url_hash -> 32-byte exact hash seek with verification",
        "engineExplanation": "Brilliant! Instead of indexing variable-length 2KB strings, indexing a 32-byte binary SHA-256 hash keeps the B-Tree ultra-compact, lightning fast, and immune to index key length limits.",
      },
      {
        "id": "strat_prefix_index_mysql",
        "title": "MySQL Prefix Index: url(255)",
        "sqlCommand": "CREATE INDEX idx_url_prefix ON web_bookmarks(url(255));",
        "isOptimal": False,
        "resultingCost": 1500,
        "resultingLatencyMs": 85,
        "executionPlanSummary": "Index Scan on prefix -> Cannot be used for covering index or exact sort",
        "engineExplanation": "Partial solution: Prefix indexes cannot be used for index-only scans, and URLs sharing identical long domain prefixes degrade to leaf scans.",
      },
      {
        "id": "strat_fulltext_index_url",
        "title": "Fulltext Search Index on url",
        "sqlCommand": "CREATE FULLTEXT INDEX idx_url_ft ON web_bookmarks(url);",
        "isOptimal": False,
        "resultingCost": 12000,
        "resultingLatencyMs": 140,
        "executionPlanSummary": "Fulltext Index Parse -> Tokenizes URL on punctuation, causing false positives",
        "engineExplanation": "Fulltext indexes split on slashes and dots, breaking exact URL lookup semantics.",
      },
    ],
    "keyTakeaway": "Never index long text columns (URLs, payloads) directly. Store a deterministic cryptographic hash (MD5 or SHA256) in a generated column and index the compact hash for instant equality seeks.",
  },
  {
    "id": "or_filter_index_merge_failure",
    "title": "OR Filter Across Columns Triggers Table Scan",
    "difficulty": "Junior",
    "category": "or_conditions",
    "categoryLabel": "OR Expansion & Union",
    "tableName": "users",
    "rowCount": "6,000,000 rows",
    "tableSizeDisk": "1.6 GB on disk",
    "slowQuery": """SELECT user_id, username, email, phone
FROM users
WHERE email = 'alex@example.com' OR phone = '+14155550199';""",
    "initialCost": 145000,
    "initialLatencyMs": 1780,
    "initialPlanSummary": "Seq Scan on users (cost=0.00..145000.00) Filter: ((email = '...') OR (phone = '...'))",
    "businessContext": "Login API accepts either email or phone number. Indexes exist on email and on phone separately, but the database chooses a full table scan.",
    "strategies": [
      {
        "id": "strat_union_all_rewrite_optimal",
        "title": "Rewrite OR into UNION ALL with Unique Seek",
        "sqlCommand": """SELECT user_id, username, email, phone FROM users WHERE email = 'alex@example.com'
UNION ALL
SELECT user_id, username, email, phone FROM users WHERE phone = '+14155550199' AND email <> 'alex@example.com';""",
        "isOptimal": True,
        "resultingCost": 8.4,
        "resultingLatencyMs": 1.2,
        "executionPlanSummary": "Append -> 2x Index Scans using idx_users_email and idx_users_phone",
        "engineExplanation": "Winner! An OR condition across two different columns prevents single B-Tree seeks. UNION ALL allows each branch to perform an independent, instant index seek on its respective column.",
      },
      {
        "id": "strat_composite_email_phone",
        "title": "Composite Index on (email, phone)",
        "sqlCommand": "CREATE INDEX idx_users_email_phone ON users(email, phone);",
        "isOptimal": False,
        "resultingCost": 145000,
        "resultingLatencyMs": 1780,
        "executionPlanSummary": "Seq Scan on users (Composite index cannot seek on second column when first is missing)",
        "engineExplanation": "Trap! If a user logs in with phone only, the leftmost column (email) is missing, rendering the composite index unusable for the phone half.",
      },
      {
        "id": "strat_enable_bitmap_scan",
        "title": "Rely on Postgres BitmapOr Index Merge",
        "sqlCommand": "/* Keep query as is, relying on BitmapOr */",
        "isOptimal": False,
        "resultingCost": 850,
        "resultingLatencyMs": 45,
        "executionPlanSummary": "BitmapOr on idx_email, idx_phone -> Bitmap Heap Scan",
        "engineExplanation": "BitmapOr is much better than a Seq Scan, but still 40x slower than a direct UNION ALL index seek because it must construct in-memory bitmap pages.",
      },
    ],
    "keyTakeaway": "An OR filter across different columns (colA = X OR colB = Y) prevents single index seeks. Rewriting to UNION ALL allows the optimizer to execute two independent sub-millisecond index seeks.",
  },
  {
    "id": "between_timestamp_inclusive",
    "title": "The BETWEEN 23:59:59 Microsecond Data Leak",
    "difficulty": "Junior",
    "category": "range_queries",
    "categoryLabel": "Range Queries & Boundaries",
    "tableName": "financial_ledger",
    "rowCount": "14,000,000 rows",
    "tableSizeDisk": "4.1 GB on disk",
    "slowQuery": """SELECT transaction_id, account_id, amount, posted_at
FROM financial_ledger
WHERE posted_at BETWEEN '2026-03-01 00:00:00' AND '2026-03-31 23:59:59';""",
    "initialCost": 85000,
    "initialLatencyMs": 1100,
    "initialPlanSummary": "Index Scan using idx_ledger_posted_at -> High execution time & Data Discrepancy",
    "businessContext": "Monthly accounting close query: Auditors discover that $142,000 worth of transactions posted at 23:59:59.450 on March 31st are missing from the balance sheet!",
    "strategies": [
      {
        "id": "strat_half_open_bounds_optimal",
        "title": "Half-Open Range: >= '2026-03-01' AND < '2026-04-01'",
        "sqlCommand": """SELECT transaction_id, account_id, amount, posted_at
FROM financial_ledger
WHERE posted_at >= '2026-03-01 00:00:00' 
  AND posted_at < '2026-04-01 00:00:00';""",
        "isOptimal": True,
        "resultingCost": 18.2,
        "resultingLatencyMs": 1.4,
        "executionPlanSummary": "Index Scan using idx_ledger_posted_at -> 100% Accurate & Zero Microsecond Loss",
        "engineExplanation": "Gold Standard! The half-open interval [start, next_start) captures every transaction right up to 23:59:59.999999 without relying on arbitrary precision seconds.",
      },
      {
        "id": "strat_cast_date_trunc",
        "title": "Use date_trunc('month', posted_at)",
        "sqlCommand": "SELECT * FROM financial_ledger WHERE date_trunc('month', posted_at) = '2026-03-01';",
        "isOptimal": False,
        "resultingCost": 350000,
        "resultingLatencyMs": 4800,
        "executionPlanSummary": "Seq Scan on financial_ledger (Function disables B-Tree range seek)",
        "engineExplanation": "Crashes performance: Wrapping posted_at in date_trunc() forces a full sequential scan across 14 million rows.",
      },
      {
        "id": "strat_between_with_nanos",
        "title": "Use BETWEEN '2026-03-31 23:59:59.999999'",
        "sqlCommand": "WHERE posted_at BETWEEN '2026-03-01' AND '2026-03-31 23:59:59.999999'",
        "isOptimal": False,
        "resultingCost": 22.0,
        "resultingLatencyMs": 3.8,
        "executionPlanSummary": "Index Scan -> Brittle: Breaks if timestamp precision changes from 6 to 9 digits",
        "engineExplanation": "Brittle: In MySQL or SQL Server, rounding rules can cause 23:59:59.999 to round UP to the next month's 00:00:00.000, accidentally including next month's records.",
      },
    ],
    "keyTakeaway": "Never use BETWEEN for date/timestamp intervals. BETWEEN is inclusive and drops sub-second records. Always use half-open intervals: col >= start AND col < next_start.",
  },
  {
    "id": "case_insensitive_collation",
    "title": "LOWER() Function on Username Prevents Unique Index Seek",
    "difficulty": "Junior",
    "category": "collation",
    "categoryLabel": "Collation & Case Sensitivity",
    "tableName": "auth_users",
    "rowCount": "9,000,000 rows",
    "tableSizeDisk": "2.3 GB on disk",
    "slowQuery": """SELECT user_id, password_hash
FROM auth_users
WHERE LOWER(username) = LOWER('JohnDoe_Admin');""",
    "initialCost": 195000,
    "initialLatencyMs": 2400,
    "initialPlanSummary": "Seq Scan on auth_users (cost=0.00..195000.00) Filter: (lower(username) = 'johndoe_admin'::text)",
    "businessContext": "Login authentication check verifies username case-insensitively. Table has an index on username, but LOWER() causes a 2.4-second delay on every single login attempt.",
    "strategies": [
      {
        "id": "strat_functional_lower_optimal",
        "title": "Functional Index on LOWER(username) or CITEXT data type",
        "sqlCommand": """CREATE UNIQUE INDEX idx_users_username_lower ON auth_users(LOWER(username));
-- Query:
SELECT user_id, password_hash FROM auth_users WHERE LOWER(username) = 'johndoe_admin';""",
        "isOptimal": True,
        "resultingCost": 4.1,
        "resultingLatencyMs": 0.7,
        "executionPlanSummary": "Index Scan using idx_users_username_lower -> Instant unique B-Tree seek in 0.7ms",
        "engineExplanation": "Winner! An expression index on LOWER(username) indexes the pre-lowercased string, resolving login checks in 0.7ms while enforcing case-insensitive uniqueness.",
      },
      {
        "id": "strat_remove_lower",
        "title": "Remove LOWER() from Query",
        "sqlCommand": "SELECT user_id, password_hash FROM auth_users WHERE username = 'JohnDoe_Admin';",
        "isOptimal": False,
        "resultingCost": 4.1,
        "resultingLatencyMs": 0.7,
        "executionPlanSummary": "Index Scan, but FAILS case-insensitivity requirements",
        "engineExplanation": "Breaks business requirements: If the user registered as 'johndoe_admin', logging in with 'JohnDoe_Admin' will return 0 rows under case-sensitive collations.",
      },
      {
        "id": "strat_ilike_username",
        "title": "Use ILIKE operator",
        "sqlCommand": "SELECT user_id, password_hash FROM auth_users WHERE username ILIKE 'JohnDoe_Admin';",
        "isOptimal": False,
        "resultingCost": 195000,
        "resultingLatencyMs": 2500,
        "executionPlanSummary": "Seq Scan on auth_users -> ILIKE does not use standard B-Tree index",
        "engineExplanation": "ILIKE without pg_trgm cannot use a standard B-Tree index and results in a full table scan.",
      },
    ],
    "keyTakeaway": "Standard B-Tree indexes are case-sensitive. To support case-insensitive lookups, either create an expression index on LOWER(col) or use a case-insensitive collation (CITEXT in PostgreSQL).",
  },
  {
    "id": "enum_vs_lookup_table",
    "title": "String Literal Filter on Unindexed Status Column",
    "difficulty": "Junior",
    "category": "schema_design",
    "categoryLabel": "Schema Design & Indexing",
    "tableName": "orders",
    "rowCount": "16,000,000 rows",
    "tableSizeDisk": "4.9 GB on disk",
    "slowQuery": """SELECT order_id, user_id, total_amount
FROM orders
WHERE status = 'PAYMENT_PENDING'
ORDER BY created_at ASC
LIMIT 100;""",
    "initialCost": 395000,
    "initialLatencyMs": 4800,
    "initialPlanSummary": "Seq Scan on orders (cost=0.00..395000.00) Filter: (status = 'PAYMENT_PENDING') -> Sort on created_at",
    "businessContext": "Payment reaper worker queries pending orders to cancel expired sessions. The table has 16M records, and the reaper job times out every 5 minutes.",
    "strategies": [
      {
        "id": "strat_partial_status_created_optimal",
        "title": "Partial Index on Pending Orders: (created_at ASC) WHERE status = 'PAYMENT_PENDING'",
        "sqlCommand": """CREATE INDEX idx_orders_pending_reaper 
ON orders(created_at ASC) 
WHERE status = 'PAYMENT_PENDING';""",
        "isOptimal": True,
        "resultingCost": 6.8,
        "resultingLatencyMs": 0.9,
        "executionPlanSummary": "Index Scan using idx_orders_pending_reaper -> 0.9ms instant queue drainage",
        "engineExplanation": "Masterpiece! Only 0.1% of orders are in 'PAYMENT_PENDING' at any moment. A partial index contains only pending orders pre-sorted by created_at. The reaper drains orders in 0.9ms with zero filesort.",
      },
      {
        "id": "strat_composite_full_status_created",
        "title": "Full Composite Index on (status, created_at ASC)",
        "sqlCommand": "CREATE INDEX idx_orders_status_created ON orders(status, created_at ASC);",
        "isOptimal": False,
        "resultingCost": 45.0,
        "resultingLatencyMs": 8.5,
        "executionPlanSummary": "Index Scan (Works, but index is 480 MB instead of 1.2 MB)",
        "engineExplanation": "Acceptable, but wasteful: A full composite index indexes all 16M completed and archived orders, consuming 400x more RAM than a partial index.",
      },
      {
        "id": "strat_single_status_index",
        "title": "Single Column Index on status",
        "sqlCommand": "CREATE INDEX idx_orders_status ON orders(status);",
        "isOptimal": False,
        "resultingCost": 85000,
        "resultingLatencyMs": 1400,
        "executionPlanSummary": "Bitmap Heap Scan on status -> External merge sort on created_at",
        "engineExplanation": "Still requires an expensive sort because the single-column index on status does not provide created_at order.",
      },
    ],
    "keyTakeaway": "For queue-like status tables where workers constantly poll unfinished tasks (PENDING, PROCESSING), a Partial Index with a WHERE condition eliminates 99% of index bloat and delivers sub-millisecond seeks.",
  },
  {
    "id": "correlated_subquery_in_select",
    "title": "Correlated Scalar Subquery Multiplies Execution Cost",
    "difficulty": "Junior",
    "category": "subqueries",
    "categoryLabel": "Subqueries & Joins",
    "tableName": "customers",
    "rowCount": "100,000 rows",
    "tableSizeDisk": "25 MB on disk",
    "slowQuery": """SELECT c.customer_id, c.full_name,
       (SELECT COUNT(*) FROM orders o WHERE o.customer_id = c.customer_id) AS order_count
FROM customers c
LIMIT 1000;""",
    "initialCost": 85400,
    "initialLatencyMs": 2850,
    "initialPlanSummary": "Seq Scan on customers -> SubPlan 1 executed 1,000 times (N+1 database query engine loop)",
    "businessContext": "Customer list page loads 1,000 records. A scalar subquery in the SELECT clause executes 1,000 separate queries under the hood, freezing the web response.",
    "strategies": [
      {
        "id": "strat_left_join_group_by_optimal",
        "title": "Rewrite to LEFT JOIN with Subquery Aggregation",
        "sqlCommand": """SELECT c.customer_id, c.full_name, COALESCE(o.order_count, 0) AS order_count
FROM (SELECT customer_id, full_name FROM customers LIMIT 1000) c
LEFT JOIN (
    SELECT customer_id, COUNT(*) AS order_count 
    FROM orders 
    GROUP BY customer_id
) o ON o.customer_id = c.customer_id;""",
        "isOptimal": True,
        "resultingCost": 32.0,
        "resultingLatencyMs": 3.4,
        "executionPlanSummary": "Hash Left Join between 1,000 customers and aggregated orders -> 3.4ms",
        "engineExplanation": "Winner! By pre-limiting customers to 1,000 rows and joining against an aggregated result, the database replaces 1,000 separate index seeks with a single fast hash join.",
      },
      {
        "id": "strat_index_orders_customer",
        "title": "Add Index on orders(customer_id) without Rewriting",
        "sqlCommand": "CREATE INDEX idx_orders_customer_id ON orders(customer_id);",
        "isOptimal": False,
        "resultingCost": 12500,
        "resultingLatencyMs": 420,
        "executionPlanSummary": "Index Only Scan executed 1,000 separate times in a nested loop",
        "engineExplanation": "Partial fix: Index helps the subquery, but executing 1,000 separate subplans still incurs massive function call overhead inside the query executor.",
      },
      {
        "id": "strat_lateral_join_without_index",
        "title": "Convert to CROSS JOIN LATERAL without Index",
        "sqlCommand": "SELECT c.customer_id, o.cnt FROM customers c, LATERAL (SELECT count(*) cnt FROM orders o WHERE o.customer_id = c.customer_id) o LIMIT 1000;",
        "isOptimal": False,
        "resultingCost": 85400,
        "resultingLatencyMs": 2850,
        "executionPlanSummary": "Identical nested loop execution",
        "engineExplanation": "LATERAL joins with correlated filters are physically identical to correlated scalar subqueries.",
      },
    ],
    "keyTakeaway": "Avoid correlated scalar subqueries in the SELECT projection list. They force the query engine into an internal N+1 loop. Replace them with JOINs on pre-aggregated subqueries.",
  },
  {
    "id": "distinct_on_low_cardinality",
    "title": "Slow DISTINCT on 20-Million-Row Table",
    "difficulty": "Junior",
    "category": "aggregations",
    "categoryLabel": "Distinct & Skip Scan",
    "tableName": "audit_events",
    "rowCount": "20,000,000 rows",
    "tableSizeDisk": "6.2 GB on disk",
    "slowQuery": """SELECT DISTINCT tenant_id
FROM audit_events;""",
    "initialCost": 520000,
    "initialLatencyMs": 6400,
    "initialPlanSummary": "HashAggregate on audit_events (cost=0.00..520000.00) -> Scans all 20,000,000 rows into 128MB hash table",
    "businessContext": "Tenant dropdown in superadmin dashboard needs a list of all active tenant IDs (only ~150 distinct tenants exist among 20M rows). Query takes 6.4 seconds.",
    "strategies": [
      {
        "id": "strat_recursive_loose_index_optimal",
        "title": "Emulate Loose Index Scan (Skip Scan) via Recursive CTE",
        "sqlCommand": """WITH RECURSIVE t AS (
   (SELECT tenant_id FROM audit_events ORDER BY tenant_id LIMIT 1)
   UNION ALL
   SELECT (SELECT tenant_id FROM audit_events WHERE tenant_id > t.tenant_id ORDER BY tenant_id LIMIT 1)
   FROM t WHERE t.tenant_id IS NOT NULL
)
SELECT tenant_id FROM t WHERE tenant_id IS NOT NULL;""",
        "isOptimal": True,
        "resultingCost": 15.0,
        "resultingLatencyMs": 1.2,
        "executionPlanSummary": "150 B-Tree Seeks using idx_audit_tenant -> 1.2ms (Zero full table scan)",
        "engineExplanation": "Legendary technique! Instead of scanning 20 million rows, the recursive CTE performs exactly 150 B-Tree seeks (one per distinct tenant), jumping directly from one tenant to the next in 1.2ms!",
      },
      {
        "id": "strat_index_tenant_id",
        "title": "Standard B-Tree Index on tenant_id with SELECT DISTINCT",
        "sqlCommand": "CREATE INDEX idx_audit_tenant ON audit_events(tenant_id); SELECT DISTINCT tenant_id FROM audit_events;",
        "isOptimal": False,
        "resultingCost": 185000,
        "resultingLatencyMs": 2200,
        "executionPlanSummary": "Index Only Scan -> Still reads all 20,000,000 index pointers sequentially",
        "engineExplanation": "Postgres does not have native Index Skip Scan for B-trees yet. A standard DISTINCT still walks every single leaf node in the index, scanning 20M pointers.",
      },
      {
        "id": "strat_group_by_tenant",
        "title": "Rewrite to GROUP BY tenant_id",
        "sqlCommand": "SELECT tenant_id FROM audit_events GROUP BY tenant_id;",
        "isOptimal": False,
        "resultingCost": 520000,
        "resultingLatencyMs": 6400,
        "executionPlanSummary": "HashAggregate -> Identical plan to SELECT DISTINCT",
        "engineExplanation": "DISTINCT and GROUP BY are translated to the same physical HashAggregate or GroupAggregate nodes in the optimizer.",
      },
    ],
    "keyTakeaway": "Finding a few distinct values in a massive table using SELECT DISTINCT scans the entire table or index. Emulating a Loose Index Scan (Skip Scan) with a Recursive CTE jumps directly between distinct keys in milliseconds.",
  },
  {
    "id": "index_condition_pushdown_icp",
    "title": "Index Condition Pushdown (ICP) Optimization",
    "difficulty": "Junior",
    "category": "engine_mechanics",
    "categoryLabel": "Engine Pushdown Optimization",
    "tableName": "employees",
    "rowCount": "5,000,000 rows",
    "tableSizeDisk": "1.2 GB on disk",
    "slowQuery": """SELECT employee_id, first_name, last_name, salary
FROM employees
WHERE department_id = 12 AND last_name LIKE '%son';""",
    "initialCost": 95000,
    "initialLatencyMs": 1250,
    "initialPlanSummary": "Index Scan on department_id -> 250,000 rows fetched into MySQL Server layer to evaluate LIKE '%son'",
    "businessContext": "Internal HR directory filters employees in engineering (dept 12) whose name ends in 'son'. Query visits 250,000 table rows one-by-one.",
    "strategies": [
      {
        "id": "strat_composite_icp_optimal",
        "title": "Composite Index on (department_id, last_name) with ICP",
        "sqlCommand": "CREATE INDEX idx_emp_dept_name ON employees(department_id, last_name) INCLUDE (salary);",
        "isOptimal": True,
        "resultingCost": 12.0,
        "resultingLatencyMs": 1.4,
        "executionPlanSummary": "Index Condition Pushdown (Using index condition) -> Storage engine filters in-place",
        "engineExplanation": "Winner! With Index Condition Pushdown (ICP), the InnoDB storage engine evaluates last_name LIKE '%son' directly in the B-Tree leaf pages before fetching rows from the clustered index, cutting heap reads by 99%!",
      },
      {
        "id": "strat_index_last_name_only",
        "title": "Index on last_name only",
        "sqlCommand": "CREATE INDEX idx_emp_last_name ON employees(last_name);",
        "isOptimal": False,
        "resultingCost": 95000,
        "resultingLatencyMs": 1250,
        "executionPlanSummary": "Seq Scan -> Leading wildcard '%son' completely disables index seek",
        "engineExplanation": "Leading wildcards cannot seek on last_name index.",
      },
      {
        "id": "strat_disable_icp",
        "title": "Disable ICP with SET optimizer_switch='index_condition_pushdown=off'",
        "sqlCommand": "SET optimizer_switch='index_condition_pushdown=off';",
        "isOptimal": False,
        "resultingCost": 180000,
        "resultingLatencyMs": 2800,
        "executionPlanSummary": "Forces server layer to read every clustered record",
        "engineExplanation": "Disabling ICP increases round-trips between storage engine and SQL server tier.",
      },
    ],
    "keyTakeaway": "Include secondary filter columns in composite indexes even if they contain wildcard or non-seekable operators. Index Condition Pushdown (ICP) filters rows in the storage engine before expensive heap page access.",
  },
  {
    "id": "insert_on_duplicate_key_burn",
    "title": "Auto-Increment Sequence Burn in High-Frequency UPSERT",
    "difficulty": "Junior",
    "category": "upsert",
    "categoryLabel": "UPSERT & Sequence Exhaustion",
    "tableName": "video_views",
    "rowCount": "8,000,000 rows",
    "tableSizeDisk": "1.9 GB on disk",
    "slowQuery": """-- Executed 5,000 times/sec:
INSERT INTO video_views (id, video_id, view_count)
VALUES (DEFAULT, 40129, 1)
ON DUPLICATE KEY UPDATE view_count = view_count + 1;""",
    "initialCost": 15.0,
    "initialLatencyMs": 2.2,
    "initialPlanSummary": "Upsert on unique key -> INT Primary Key burns 5,000 sequence IDs per second!",
    "businessContext": "Viral video analytics: An INT primary key (limit 2.14 billion) ran out of IDs in 3 weeks, throwing 'Duplicate entry for key PRIMARY' and taking down the entire streaming platform.",
    "strategies": [
      {
        "id": "strat_natural_key_or_bigint_optimal",
        "title": "Drop Auto-Increment ID, Use video_id as PRIMARY KEY",
        "sqlCommand": """-- video_id is already unique! Eliminate artificial auto-increment ID:
ALTER TABLE video_views DROP COLUMN id, ADD PRIMARY KEY (video_id);
-- Or change to BIGINT with innodb_autoinc_lock_mode = 2.""",
        "isOptimal": True,
        "resultingCost": 3.0,
        "resultingLatencyMs": 0.5,
        "executionPlanSummary": "Zero auto-increment sequence consumption -> In-place B-tree update",
        "engineExplanation": "Champion! In MySQL InnoDB, INSERT ... ON DUPLICATE KEY UPDATE consumes an auto-increment ID from the global table counter on every execution, even when updating an existing row. Making video_id the natural PK stops sequence burning permanently.",
      },
      {
        "id": "strat_ignore_error",
        "title": "Use INSERT IGNORE",
        "sqlCommand": "INSERT IGNORE INTO video_views VALUES (DEFAULT, 40129, 1);",
        "isOptimal": False,
        "resultingCost": 15.0,
        "resultingLatencyMs": 2.2,
        "executionPlanSummary": "Still burns auto-increment IDs on every duplicate collision",
        "engineExplanation": "INSERT IGNORE also consumes and discards auto-increment IDs for every ignored row.",
      },
      {
        "id": "strat_truncate_table",
        "title": "Truncate and Reset Auto-Increment Periodically",
        "sqlCommand": "ALTER TABLE video_views AUTO_INCREMENT = 1;",
        "isOptimal": False,
        "resultingCost": 0.0,
        "resultingLatencyMs": 0.0,
        "executionPlanSummary": "Cannot reset auto_increment below current MAX(id)",
        "engineExplanation": "In InnoDB, you cannot reset auto_increment below the highest existing value in the table without deleting rows.",
      },
    ],
    "keyTakeaway": "In MySQL, ON DUPLICATE KEY UPDATE consumes an auto-increment ID before evaluating uniqueness. On existing rows, that ID is discarded forever. Use natural primary keys or BIGINT to prevent sequence exhaustion.",
  },
]
