/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Engineering Knowledge Base",
  "tagline": "Internal technical documentation",
  "url": "https://minhkhuong2404.github.io",
  "baseUrl": "/docusaurus-knowledge-base-template/",
  "organizationName": "minhkhuong2404",
  "projectName": "docusaurus-knowledge-base-template",
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "routeBasePath": "/"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "prism": {
      "theme": {
        "plain": {
          "backgroundColor": "#1e1e2e",
          "color": "#cdd6f4"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#6c7086",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#bac2de"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "char",
              "template-string",
              "attr-value"
            ],
            "style": {
              "color": "#a6e3a1"
            }
          },
          {
            "types": [
              "number",
              "boolean"
            ],
            "style": {
              "color": "#fab387"
            }
          },
          {
            "types": [
              "keyword",
              "important",
              "atrule"
            ],
            "style": {
              "color": "#cba6f7"
            }
          },
          {
            "types": [
              "function",
              "class-name"
            ],
            "style": {
              "color": "#89b4fa"
            }
          },
          {
            "types": [
              "builtin"
            ],
            "style": {
              "color": "#f38ba8"
            }
          },
          {
            "types": [
              "tag",
              "selector"
            ],
            "style": {
              "color": "#f38ba8"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "#f9e2af"
            }
          },
          {
            "types": [
              "variable",
              "constant",
              "symbol"
            ],
            "style": {
              "color": "#f5c2e7"
            }
          },
          {
            "types": [
              "operator",
              "entity",
              "url"
            ],
            "style": {
              "color": "#89dceb"
            }
          },
          {
            "types": [
              "regex"
            ],
            "style": {
              "color": "#a6e3a1"
            }
          },
          {
            "types": [
              "property"
            ],
            "style": {
              "color": "#89dceb"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "#f38ba8"
            }
          },
          {
            "types": [
              "inserted"
            ],
            "style": {
              "color": "#a6e3a1"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "#f9e2af"
            }
          }
        ]
      },
      "additionalLanguages": [
        "java",
        "bash",
        "json",
        "yaml",
        "properties",
        "docker",
        "groovy",
        "sql"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "dark",
      "respectPrefersColorScheme": true,
      "disableSwitch": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "navbar": {
      "hideOnScroll": false,
      "items": []
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenLinks": "throw",
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
