/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Engineering Knowledge Base",
  "tagline": "Internal technical documentation",
  "url": "https://luminhkhuong.dev",
  "baseUrl": "/",
  "organizationName": "minhkhuong2404",
  "projectName": "docusaurus-knowledge-base-template",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true,
      "siteStorageNamespacing": true,
      "fasterByDefault": true,
      "mdx1CompatDisabledByDefault": true
    },
    "faster": {
      "swcJsLoader": true,
      "swcJsMinimizer": true,
      "swcHtmlMinimizer": true,
      "lightningCssMinimizer": true,
      "mdxCrossCompilerCache": true,
      "rspackBundler": true,
      "rspackPersistentCache": true,
      "ssgWorkerThreads": true,
      "gitEagerVcs": true
    },
    "experimental_vcs": {},
    "experimental_router": "browser"
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "routeBasePath": "/",
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": true,
          "remarkPlugins": [
            null
          ]
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "gtag": {
          "trackingID": "G-79SQQZQMCX",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "themes": [
    [
      "/Users/lukhuong/Desktop/docusaurus-knowledge-base-template/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "indexDocs": true,
        "indexBlog": false,
        "indexPages": false,
        "docsRouteBasePath": "/",
        "language": [
          "en"
        ],
        "highlightSearchTermsOnTargetPage": false,
        "explicitSearchResultPath": false,
        "searchResultLimits": 8,
        "searchBarShortcut": false,
        "searchBarShortcutHint": false,
        "hashed": true
      }
    ]
  ],
  "themeConfig": {
    "metadata": [
      {
        "name": "keywords",
        "content": "development, blog, software, programming, engineering"
      },
      {
        "name": "description",
        "content": "A knowledge base for software engineers to share and document technical information."
      },
      {
        "name": "author",
        "content": "Khuong Lu"
      },
      {
        "name": "viewport",
        "content": "width=device-width, initial-scale=1.0"
      },
      {
        "name": "robots",
        "content": "index, follow"
      },
      {
        "name": "theme-color",
        "content": "#000000"
      },
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      },
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black-translucent"
      },
      {
        "name": "format-detection",
        "content": "telephone=no"
      },
      {
        "name": "msapplication-TileColor",
        "content": "#000000"
      },
      {
        "name": "msapplication-config",
        "content": "/browserconfig.xml"
      }
    ],
    "headTags": [
      {
        "tagName": "link",
        "attributes": {
          "rel": "dns-prefetch",
          "href": "https://fonts.googleapis.com"
        }
      },
      {
        "tagName": "link",
        "attributes": {
          "rel": "dns-prefetch",
          "href": "https://fonts.gstatic.com"
        }
      },
      {
        "tagName": "link",
        "attributes": {
          "rel": "preconnect",
          "href": "https://fonts.googleapis.com"
        }
      },
      {
        "tagName": "link",
        "attributes": {
          "rel": "preconnect",
          "href": "https://fonts.gstatic.com",
          "crossorigin": "anonymous"
        }
      },
      {
        "tagName": "link",
        "attributes": {
          "rel": "preload",
          "as": "style",
          "href": "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
        }
      },
      {
        "tagName": "link",
        "attributes": {
          "rel": "stylesheet",
          "href": "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
        }
      }
    ],
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "title": "Engineering Knowledge Base",
      "logo": {
        "alt": "Engineering Knowledge Base Logo",
        "src": "/logo.svg",
        "srcDark": "/logo-dark.svg"
      },
      "items": [
        {
          "to": "/login",
          "label": "💎 VIP Login",
          "position": "right",
          "className": "premium-nav-button"
        },
        {
          "type": "search",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "prism": {
      "theme": {
        "plain": {
          "backgroundColor": "#eff1f5",
          "color": "#24324f"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#74839c",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#1f2a44"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.72
            }
          },
          {
            "types": [
              "string",
              "char",
              "template-string",
              "attr-value"
            ],
            "style": {
              "color": "#0f9d58"
            }
          },
          {
            "types": [
              "number",
              "boolean"
            ],
            "style": {
              "color": "#f59e0b",
              "fontWeight": "500"
            }
          },
          {
            "types": [
              "keyword",
              "important",
              "atrule"
            ],
            "style": {
              "color": "#2f9e44",
              "fontWeight": "600"
            }
          },
          {
            "types": [
              "function",
              "class-name"
            ],
            "style": {
              "color": "#39ff14",
              "fontWeight": "600"
            }
          },
          {
            "types": [
              "builtin"
            ],
            "style": {
              "color": "#51cf66"
            }
          },
          {
            "types": [
              "tag",
              "selector"
            ],
            "style": {
              "color": "#51cf66"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "#2f9e44"
            }
          },
          {
            "types": [
              "variable",
              "constant",
              "symbol"
            ],
            "style": {
              "color": "#1f7a33"
            }
          },
          {
            "types": [
              "operator",
              "entity",
              "url"
            ],
            "style": {
              "color": "#39ff14"
            }
          },
          {
            "types": [
              "regex"
            ],
            "style": {
              "color": "#1f9d00"
            }
          },
          {
            "types": [
              "property"
            ],
            "style": {
              "color": "#39ff14"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "#51cf66",
              "textDecorationLine": "line-through"
            }
          },
          {
            "types": [
              "inserted"
            ],
            "style": {
              "color": "#1f9d00",
              "textDecorationLine": "underline"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "#f59e0b",
              "fontWeight": "600"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "backgroundColor": "#161923",
          "color": "#e8eaf3"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#8d93ab",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#cfd4e8"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "char",
              "template-string",
              "attr-value"
            ],
            "style": {
              "color": "#8ef7b2"
            }
          },
          {
            "types": [
              "number",
              "boolean"
            ],
            "style": {
              "color": "#ffb86c",
              "fontWeight": "500"
            }
          },
          {
            "types": [
              "keyword",
              "important",
              "atrule"
            ],
            "style": {
              "color": "#ff7ac6",
              "fontWeight": "600"
            }
          },
          {
            "types": [
              "function",
              "class-name"
            ],
            "style": {
              "color": "#8ef7b2",
              "fontWeight": "600"
            }
          },
          {
            "types": [
              "builtin"
            ],
            "style": {
              "color": "#ff8fab"
            }
          },
          {
            "types": [
              "tag",
              "selector"
            ],
            "style": {
              "color": "#ff8fab"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "#ffe08a"
            }
          },
          {
            "types": [
              "variable",
              "constant",
              "symbol"
            ],
            "style": {
              "color": "#ed84f9"
            }
          },
          {
            "types": [
              "operator",
              "entity",
              "url"
            ],
            "style": {
              "color": "#6df6b2"
            }
          },
          {
            "types": [
              "regex"
            ],
            "style": {
              "color": "#6df6b2"
            }
          },
          {
            "types": [
              "property"
            ],
            "style": {
              "color": "#6df6b2"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "#ff8fab",
              "textDecorationLine": "line-through"
            }
          },
          {
            "types": [
              "inserted"
            ],
            "style": {
              "color": "#8ef7b2",
              "textDecorationLine": "underline"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "#ffe08a",
              "fontWeight": "600"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "json",
        "yaml"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "dark",
      "respectPrefersColorScheme": true,
      "disableSwitch": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "LinkedIn",
          "items": [
            {
              "label": "luminhkhuong",
              "href": "https://www.linkedin.com/in/luminhkhuong/"
            }
          ]
        },
        {
          "title": "GitHub",
          "items": [
            {
              "label": "minhkhuong2404",
              "href": "https://github.com/minhkhuong2404"
            }
          ]
        },
        {
          "title": "Facebook",
          "items": [
            {
              "label": "luminhkhuong",
              "href": "https://www.facebook.com/luminhkhuong/"
            }
          ]
        },
        {
          "title": "Leetcode",
          "items": [
            {
              "label": "luminhkhuong",
              "href": "https://leetcode.com/u/luminhkhuong/"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 by Khuong Lu,  Dev. Built with Docusaurus and Github Page. ❤️"
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "storage": {
    "type": "localStorage",
    "namespace": true
  },
  "onBrokenLinks": "throw",
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": false,
      "admonitions": false,
      "headingIds": false
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
